---
title: "Winter_DH_Germination_barley_analysis"
author: "Karl Kunze"
date: "10/26/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---
reading in files
```{r}
getwd()
library(readxl)

TP1_half<-as.data.frame(read.csv("data/Winter_DH/TP1/DHtp1_full_F.csv",stringsAsFactors = FALSE))
TP2<-as.data.frame(read.csv("data/Winter_DH/TP2/DHtp2_all_F.csv",stringsAsFactors = FALSE))
TP3<-as.data.frame(read.csv("data/Winter_DH/TP3/DHtp3_all_F.csv",stringsAsFactors = FALSE))

str(TP1)
str(TP2)
str(TP3)
TP_all<-rbind(TP1_half,TP2,TP3)
```
add field phenotype data
```{r}
DH_2020_Snyder<-as.data.frame(read_excel("data/Winter_DH/WMB_DH_2020_kkGit.xlsx",sheet = "Snyder"))
DH_2020_Ketola<-as.data.frame(read_excel("data/Winter_DH/WMB_DH_2020_kkGit.xlsx",sheet = "Ketola"))
DH_2020_PHS<-as.data.frame(read.csv("data/Winter_DH/WMB_DH_2020_Ketola_PHS.csv",stringsAsFactors = TRUE))

DH_2020_field<-rbind(DH_2020_Snyder,DH_2020_Ketola)

DH_2020_field<-merge(DH_2020_field,DH_2020_PHS,by=c("PLOT","Entry"),all.x = TRUE)

```
converting PHS scores
```{r}
str(DH_2020_field)
str(TP_all)
colnames(DH_2020_field)
#reduce 
# Phs conversion
five_avg=function(df,pheno,new_pheno,missing_phenos=F){
  df[[pheno]]=as.numeric(df[[pheno]])
  df <- cbind(df, "ID" = outer(df[[pheno]], 10^c(4:0), function(a, b) a %/% b %% 10))
  if(missing_phenos==T){
    df$ID.1[which(df$note=="*")]=NA
  }
  df$new_pheno=apply(df[,c((ncol(df)-4):ncol(df))],1,function(x) mean(x, na.rm=T))
  df$new_pheno=as.numeric(df$new_pheno)
  # df$var=as.numeric(apply(df[,c((ncol(df)-4):ncol(df))], 1,var))
  #df$sd=as.numeric(apply(df[,c((ncol(df)-5):(ncol(df)-1))], 1,function(x) sd(x, na.rm=T)))
  #df=df[,c(1:(ncol(df)-9),(ncol(df)-2),(ncol(df)-1), ncol(df))]

}



DH_2020_field$Sprout.Score
DH_2020_field$phs=five_avg(df=DH_2020_field,pheno='Sprout.Score',new_pheno='phs')
DH_2020_field$phs
  

```


```{r}
colnames(TP_all)
df<-TP_all
colnames(df)
Germ_traits=function(df){
  df$GE=apply(df[,8:13],1,function(x) {sum(as.numeric(x[1:3]))/sum(as.numeric(x[1:6]))})  #does not count dead kernels in total count
  #df$GC=apply(df[,6:10],1,function(x) {sum(as.numeric(x[1:4]))/sum(as.numeric(x[1:5]))}) #does count dead kernels
  df$GI=apply(df[,8:13],1, function(x) {(sum(as.numeric(x[1:3]))/(as.numeric(x[1])+2*as.numeric(x[2])+ 3*as.numeric(x[3])))*10})
  df$GIscale=apply(df[,c(13,14)],1, function(x) {as.numeric(x[1])*as.numeric(x[2])}) #GI*GE
  df$GE_5D=apply(df[,8:13],1,function(x) {sum(as.numeric(x[1:5]))/sum(as.numeric(x[1:6]))})
  df$Plus_PM=as.factor(df$PM_at_plating)
 
  df$replication=as.factor(df$replication)
  df$Timepoint=as.factor(df$Timepoint)
  df
}
TPall=Germ_traits(TP_all)
colnames(TPall)
colnames(DH_2020_field)
All_pheno_TPall<-merge(DH_2020_field,TPall,by=c("PLOT","Entry","Location"),all = TRUE)
str(All_pheno_TPall)
View(All_pheno_TPall)
save(All_pheno_TPall, file="WMB DH 2020 all data for analysis.RData")

```

