---
title: "Winter_DH_Germination_barley_analysis"
author: "Karl Kunze"
date: "10/26/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---
Workflow:
Winter_DH_data_consolidation.Rmd ->analysis_script.R->WDH_GenotypeData_Processing.Rmd

reading in files
```{r}
path<-"C:/Users/Karl/git/BarleyGermination-KK"
setwd(path)
getwd()

library(readxl)

TP1_half<-as.data.frame(read.csv("data/Winter_DH/TP1/DHtp1_full_F.csv",stringsAsFactors = FALSE))

TP2<-as.data.frame(read.csv("data/Winter_DH/TP2/DHtp2_all_F.csv",stringsAsFactors = FALSE))

TP3<-as.data.frame(read.csv("data/Winter_DH/TP3/DHtp3_all_F.csv",stringsAsFactors = FALSE))
TP4<-as.data.frame(read.csv("data/Winter_DH/TP4/DHtp4_all_combined_F.csv",stringsAsFactors = FALSE))

TP5<-as.data.frame(read.csv("data/Winter_DH/TP5/TP5_all.csv",stringsAsFactors = FALSE))
colnames(TP5)
TP5<-TP5[,-c(2,16)]
colnames(TP5)
colnames(TP4)
colnames(TP1_half)[19]<-"UserDay3"
table(TP1_half$Entry)


##



which(TP4$Entry=="Check 3-SY Tepee")

#if this is present correct it
TP4[c(1717,1718),]$Entry<-"Check 4-SY Tepee"



##
str(TP1_half)

str(TP2)
str(TP3)
str(TP4)
str(TP5)
###
library(tibble)
library(dplyr)




###
TP3KK<-TP3[TP3$replication=="2",][,c(2,8:13)]
TP3TR<-TP3[TP3$replication=="1",][,c(2,8:13)]
TP4KK<-TP4[TP4$replication=="2",][,c(2,8:13)]
TP4TR<-TP4[TP4$replication=="1",][,c(2,8:13)]

TP5KK<-TP5[TP5$replication=="2",][,c(2,8:13)]
TP5TR<-TP5[TP5$replication=="1",][,c(2,8:13)]
TP3[,c(2,8:13)]
str(TP3KK)
str(TP3TR)
cor(TP3TR$Day1Germ,TP3KK$Day1Germ,use = "complete.obs")
cor(TP3TR$Day2Germ,TP3KK$Day2Germ,use = "complete.obs")
cor(TP3TR$Day3Germ,TP3KK$Day3Germ,use = "complete.obs")
cor(TP3TR$Day4Germ,TP3KK$Day4Germ,use = "complete.obs")
cor(TP3TR$Day5Germ,TP3KK$Day5Germ,use = "complete.obs")
cor(TP5TR$Day5Germ,TP5KK$Day3Germ,use = "complete.obs")

TP3KKmean <- colMeans(TP3KK[,2:7], na.rm=TRUE)
TP3TRmean <- colMeans(TP3TR[,2:7],na.rm=TRUE)

TP4KKmean <- colMeans(TP4KK[,2:7], na.rm=TRUE)
TP4TRmean <- colMeans(TP4TR[,2:7],na.rm=TRUE)

cor(TP4TR$Day1Germ,TP4KK$Day1Germ,use = "complete.obs")
cor(TP4TR$Day2Germ,TP4KK$Day2Germ,use = "complete.obs")
cor(TP4TR$Day3Germ,TP4KK$Day3Germ,use = "complete.obs")
cor(TP4TR$Day4Germ,TP4KK$Day4Germ,use = "complete.obs")
cor(TP4TR$Day5Germ,TP4KK$Day5Germ,use = "complete.obs")

corday3<-merge(TP3[TP3$UserDay5=="KK",][,c(2,8:13)],TP3[TP3$UserDay5=="TR",][,c(2,8:13)],by="Entry")


colnames(TP5)[1]<-"ï.."
TPall<-rbind(TP1_half,TP2,TP3,TP4,TP5)

colnames(TP1_half)
colnames(TP2)
colnames(TP3)
colnames(TP4)
colnames(TP5)
table(TPall$Entry)
#need to remove a1023 a1024,etc... PLOTS at Snyder location
table(TPall$PLOT)

TPall$PLOT<-gsub("a","",(TPall$PLOT))
table(TPall$PLOT)
TPall[TPall$PLOT==11303,]
TPall[TPall$Entry=="BBBdormSNLine",]$PLOT<-13001
TPall[TPall$Entry=="BBBdormSRLine",]$PLOT<-13002
#table(TPall$PLOT)
TPall$PLOT<-as.numeric(TPall$PLOT)
#I'm giving SN and SR lines arbitrary plot numbers to remove characters in the plot column. Plot numbers should sort them to end of the dataframe
TPall<-TPall[with(TPall, order(PLOT, replication)),]

table(TPall$Entry)

```

```{r}


```
add field phenotype data
```{r}
DH_2020_Snyder<-as.data.frame(read_excel("data/Winter_DH/WMB_DH_2020_kkGit.xlsx",sheet = "Snyder"))
DH_2020_Ketola<-as.data.frame(read_excel("data/Winter_DH/WMB_DH_2020_kkGit.xlsx",sheet = "Ketola"))
DH_2020_PHS<-as.data.frame(read.csv("data/Winter_DH/WMB_DH_2020_Ketola_PHS.csv",stringsAsFactors = TRUE))
DH_2020_PHS<-DH_2020_PHS[!is.na(DH_2020_PHS$Sprout.Score),]

DH_2020_PHS$Sprout.Score<-as.character(DH_2020_PHS$Sprout.Score)
DH_2020_PHS[DH_2020_PHS$Sprout.Score=="0",]$Sprout.Score<-"00000"

table(DH_2020_PHS$Sprout.Score)
str(DH_2020_PHS$Sprout.Score)

str(DH_2020_Snyder$HD)



which(DH_2020_PHS$Entry=="Check 3-DH130911")
#change
DH_2020_PHS[12,]$Entry<-"Check 3-DH130910"
which(DH_2020_Snyder$Entry=="Check 4-SY Tepee")
#4 103 203 303 403 503
#DH_2020_Snyder[c(4,103,203,303,403,503),]$Entry<-"Check 4-SY Tepee"
table(DH_2020_Ketola$Entry)
DH_2020_field<-rbind(DH_2020_Snyder,DH_2020_Ketola)
##issue with Ketola and Snyder of DH130910 naming
DH_2020_field<-merge(DH_2020_field,DH_2020_PHS,by=c("PLOT","Entry"),all = TRUE)

```

```{r}
str(DH_2020_field)
str(TPall)
colnames(DH_2020_field)
table(DH_2020_field$Pedigree)
#change naming of DH130910/Wintmalt to Wintmalt/DH130910, makes for easier plotting
DH_2020_field[DH_2020_field$Pedigree=="DH130910/Wintmalt",]$Pedigree<-"Wintmalt/DH130910"
str(DH_2020_field)

```
Use names below
```{r}
table(DH_2020_field$Entry)

```
converting PHS scores and heading date
```{r}

#reduce 
# Phs conversion
five_avg=function(df,pheno,new_pheno,missing_phenos=F){
  df[[pheno]]=as.numeric(df[[pheno]])
  df <- cbind(df, "ID" = outer(df[[pheno]], 10^c(4:0), function(a, b) a %/% b %% 10))
  if(missing_phenos==T){
    df$ID.1[which(df$note=="*")]=NA
  }
  df$new_pheno=apply(df[,c((ncol(df)-4):ncol(df))],1,function(x) mean(x, na.rm=T))
  df$new_pheno=as.numeric(df$new_pheno)
  # df$var=as.numeric(apply(df[,c((ncol(df)-4):ncol(df))], 1,var))
  #df$sd=as.numeric(apply(df[,c((ncol(df)-5):(ncol(df)-1))], 1,function(x) sd(x, na.rm=T)))
  #df=df[,c(1:(ncol(df)-9),(ncol(df)-2),(ncol(df)-1), ncol(df))]

}



DH_2020_field$phs=five_avg(df=DH_2020_field,pheno='Sprout.Score',new_pheno='phs')
table(DH_2020_PHS$Sprout.Score)
hist(DH_2020_field$phs)

typeof(DH_2020_field$HD)
#####
##################
DH_2020_field$HD<-as.numeric(DH_2020_field$HD)
julian_days=function(df, cutoff){
  may=31+29+31+30
  june=may+31
  #july=june+30
  
  s=which(df$HD<cutoff)
  a=which(df$HD>cutoff)
  df$HD[a]=df$HD[a]+may
  df$HD[s]=df$HD[s]+june
  df$HD
  
}
DH_2020_field$HD<-julian_days(DH_2020_field, 25 )



####
#OSU18_OSU19_1$HD_c
#OSU18_OSU19_1$HD_c <- as.Date(OSU18_OSU19_1$HD_c, format = "%y-%b-%d")
#Converted all to Julian Date
#OSU18_OSU19_1$HD_c <- as.numeric(format(OSU18_OSU19_1$HD_c, "%j"))
##### 

#other phenotypes

str(DH_2020_field)
DH_2020_field$mass<-as.numeric(DH_2020_field$mass)
DH_2020_field<-DH_2020_field[!is.na(DH_2020_field$PLOT),]
DH_2020_field[is.na(DH_2020_field$HD),]
DH_2020_field$`CU Plant ID`<-as.numeric(DH_2020_field$`CU Plant ID`)
table(DH_2020_field$Scald)
DH_2020_field[DH_2020_field$Scald=="x",]<-NA
hist(as.numeric(DH_2020_field[DH_2020_field$Pedigree=="Wintmalt",]$Scald))
table(DH_2020_Ketola$Pedigree)
hist(as.numeric(DH_2020_Snyder$Scald))
#we don't have enough differentiation of scald between the two locations,
#one possiblity is to either only use one location or separate by family
#checks have high scald but it may be more of poor seed quality
DH_2020_field[is.na(DH_2020_field$HD),]$Ht<-NA
DH_2020_field[is.na(DH_2020_field$PM),]$PM<-NA


table(DH_2020_field$Scald)
DH_2020_field$Scald<-as.numeric(DH_2020_field$Scald)
DH_2020_field$Ht<-as.numeric(DH_2020_field$Ht)
DH_2020_field$PM<-as.numeric(DH_2020_field$PM)
#phs dates
str(DH_2020_field)

```

#Dissecting GE, GI and GIScale for 5 day
```{r}
####taking apart functions that calculate GE, GI, GIScale to develop 5 day(5D) caluclatios
#TP_all0<-TP_all
#df<-TP_all0
#df$GE=apply(df[,8:13],1,function(x) {sum(as.numeric(x[1:3]))/sum(as.numeric(x[1:6]))})  #does not count dead kernels in total count

  #df$GC=apply(df[,6:10],1,function(x) {sum(as.numeric(x[1:4]))/sum(as.numeric(x[1:5]))}) #does count dead kernels

 # df$GI=apply(df[,8:13],1, function(x) {(sum(as.numeric(x[1:3]))/(as.numeric(x[1])+2*as.numeric(x[2])+ 3*as.numeric(x[3])))*10})


#df$GIscale=apply(df[,c(27,28)],1, function(x) {as.numeric(x[1])*as.numeric(x[2])}) #GI*GE
#df$GIscale
 # df$GE_5D=apply(df[,8:13],1,function(x) {sum(as.numeric(x[1:5]))/sum(as.numeric(x[1:6]))})

## Need to add 5 day extension to denominator of GI below

  #df$GI_5D=apply(df[,8:13],1, function(x) {(sum(as.numeric(x[1:5]))/(as.numeric(x[1])+2*as.numeric(x[2])+ 3*as.numeric(x[3])+4*as.numeric(x[4])+5*as.numeric(x[5])))*10})
 
  #df$GIscale_5D=apply(df[,c(29,30)],1, function(x) {as.numeric(x[1])*as.numeric(x[2])}) #GI*GE
  
  


```


```{r}
colnames(TPall)
Germ_traits=function(df){
  df$GE=apply(df[,8:13],1,function(x) {sum(as.numeric(x[1:3]))/sum(as.numeric(x[1:6]))})  #does not count dead kernels in total count
  #df$GC=apply(df[,6:10],1,function(x) {sum(as.numeric(x[1:4]))/sum(as.numeric(x[1:5]))}) #does count dead kernels
  df$GI=apply(df[,8:13],1, function(x) {(sum(as.numeric(x[1:3]))/(as.numeric(x[1])+2*as.numeric(x[2])+ 3*as.numeric(x[3])))*10})
  df$GIscale=apply(df[,c(27,28)],1, function(x) {as.numeric(x[1])*as.numeric(x[2])}) #GI*GE
 #5 day 
  df$GE_5D=apply(df[,8:13],1,function(x) {sum(as.numeric(x[1:5]))/sum(as.numeric(x[1:6]))})
  df$GI_5D=apply(df[,8:13],1, function(x) {(sum(as.numeric(x[1:5]))/(as.numeric(x[1])+2*as.numeric(x[2])+ 3*as.numeric(x[3])+4*as.numeric(x[4])  + 5*as.numeric(x[5]) ))*10})
  df$GIscale_5D=apply(df[,c(29,30)],1, function(x) {as.numeric(x[1])*as.numeric(x[2])}) #GI*GE
  
  df$Plus_PM=as.factor(df$PM_at_plating)
 
  df$replication=as.factor(df$replication)
  df$Timepoint=as.factor(df$Timepoint)
  df
 } 














table(TPall$Entry)
TPall=Germ_traits(TPall)
colnames(TPall)

hist(TPall$GIscale)
hist(TPall[TPall$Timepoint=="1",]$GIscale)
hist(TPall[TPall$Timepoint=="2",]$GIscale)
hist(TPall[TPall$Timepoint=="3",]$GIscale)
hist(TPall[TPall$Timepoint=="4",]$GIscale)
hist(TPall[TPall$Timepoint=="5",]$GIscale)

hist(TPall[TPall$Timepoint=="1",]$GIscale_5D)
hist(TPall[TPall$Timepoint=="2",]$GIscale_5D)
hist(TPall[TPall$Timepoint=="3",]$GIscale_5D)
hist(TPall[TPall$Timepoint=="4",]$GIscale_5D)
hist(TPall[TPall$Timepoint=="5",]$GIscale_5D)

hist(TPall[TPall$Timepoint=="1",]$GE)
hist(TPall[TPall$Timepoint=="2",]$GE)
hist(TPall[TPall$Timepoint=="3",]$GE)
hist(TPall[TPall$Timepoint=="4",]$GE)
hist(TPall[TPall$Timepoint=="5",]$GE)
     
hist(TPall[TPall$Timepoint=="1",]$GE_5D)
hist(TPall[TPall$Timepoint=="2",]$GE_5D)
hist(TPall[TPall$Timepoint=="3",]$GE_5D)
hist(TPall[TPall$Timepoint=="4",]$GE_5D)
hist(TPall[TPall$Timepoint=="5",]$GE_5D)


table(TPall$Entry)
colnames(DH_2020_field)
table(DH_2020_field$Entry)
All_pheno_TPall<-merge(DH_2020_field,TPall,by=c("PLOT","Entry","Location"),all = TRUE)
str(All_pheno_TPall)
All_pheno_TPall$GIscale_5D
All_pheno_TPall$GIscale

#View(All_pheno_TPall)
getwd()
save(All_pheno_TPall, file="WMB DH 2020 all data for analysis.RData")

```
#data analysis of phenotypes
```{r}
library(lme4)
#this will overwrite original TP files, with ones that have GE, GI and GIscale calculated
TP1<-TPall[TPall$Timepoint=="1",]
TP2<-TPall[TPall$Timepoint=="2",]
TP3<-TPall[TPall$Timepoint=="3",]
TP4<-TPall[TPall$Timepoint=="4",]
modelKK<-lm(GE_5D~Entry+Location,TP4[TP4$replication=="2",])
modelTR<-lm(GE_5D~Entry+Location,TP4[TP4$replication=="1",])



```



