---
title: "Significant_hits_GWAS"
author: "Karl Kunze"
date: "2/12/2021"
output: html_document
---

```{r}
load(here("data/GWA_results/GWA_WDH_field_phenotypes.Rdata"))
load(here("data/GWA_results/GWA_WDH_TP1.RData"))
load(here("data/GWA_results/GWA_WDH_TP2.RData"))
load(here("data/GWA_results/GWA_WDH_TP3.RData"))
load(here("data/GWA_results/GWA_WDH_TP4.RData"))
load(here("data/GWA_results/GWA_WDH_TP5.RData"))
load(here("data/GWA_results/GWA_WDH_phs.Rdata"))


#TP1
Pval<-function(i){
    sign<-0.05/nrow(i)
    sign
  i<-i[i$P.value<sign,]
  i$TP=NA
  i$Trait=NA
  i$model=NA
  return(i)
  
}

GE.TP1.blues<-Pval(GWAS.GETP1.blues.mlmm$GWAS)
GE.TP1.blues[,c('TP','Trait','model')]<-as.list(str_split_fixed(deparse(substitute(GE.TP1.blues)),"\\.",3)[c(2,1,3)])[c(1,2,3)]

GI.TP1.blues<-Pval(GWAS.GITP1.blues.mlmm$GWAS)
GI.TP1.blues[,c('TP','Trait','model')]<-as.list(str_split_fixed(deparse(substitute(GI.TP1.blues)),"\\.",3)[c(2,1,3)])[c(1,2,3)]

GE_5D.TP1.blues<-Pval(GWAS.GETP1_5D.blues.mlmm$GWAS)
GE_5D.TP1.blues[,c('TP','Trait','model')]<-as.list(str_split_fixed(deparse(substitute(GE_5D.TP1.blues)),"\\.",3)[c(2,1,3)])[c(1,2,3)]
GE_5D.TP1.blues
GI_5D.TP1.blues<-Pval(GWAS.GITP1_5D.blues.mlmm$GWAS)
GI_5D.TP1.blues[,c('TP','Trait','model')]<-as.list(str_split_fixed(deparse(substitute(GI_5D.TP1.blues)),"\\.",3)[c(2,1,3)])[c(1,2,3)]
GWAS.sign.blues<-rbind(GE.TP1.blues,GI.TP1.blues,GE_5D.TP1.blues,GI_5D.TP1.blues)

###
GE.TP1.blups<-Pval(GWAS.GETP1.blups.mlmm$GWAS)
GE.TP1.blups[,c('TP','Trait','model')]<-as.list(str_split_fixed(deparse(substitute(GE.TP1.blups)),"\\.",3)[c(2,1,3)])[c(1,2,3)]

GI.TP1.blups<-Pval(GWAS.GITP1.blups.mlmm$GWAS)
GI.TP1.blups[,c('TP','Trait','model')]<-as.list(str_split_fixed(deparse(substitute(GI.TP1.blups)),"\\.",3)[c(2,1,3)])[c(1,2,3)]

GE_5D.TP1.blups<-Pval(GWAS.GETP1_5D.blups.mlmm$GWAS)
GE_5D.TP1.blups[,c('TP','Trait','model')]<-as.list(str_split_fixed(deparse(substitute(GE_5D.TP1.blups)),"\\.",3)[c(2,1,3)])[c(1,2,3)]
GE_5D.TP1.blups
GI_5D.TP1.blups<-Pval(GWAS.GITP1_5D.blups.mlmm$GWAS)
GI_5D.TP1.blups[,c('TP','Trait','model')]<-as.list(str_split_fixed(deparse(substitute(GI_5D.TP1.blups)),"\\.",3)[c(2,1,3)])[c(1,2,3)]
GWAS.sign.blups<-rbind(GE.TP1.blups,GI.TP1.blups,GE_5D.TP1.blups,GI_5D.TP1.blups)

GWAS.sign.TP1<-rbind(GWAS.sign.blues,GWAS.sign.blups)
GWAS.sign.TP1


##TP2
GE.TP2.blues<-Pval(GWAS.GETP2.blues.mlmm$GWAS)
GE.TP2.blues[,c('TP','Trait','model')]<-as.list(str_split_fixed(deparse(substitute(GE.TP2.blues)),"\\.",3)[c(2,1,3)])[c(1,2,3)]

GI.TP2.blues<-Pval(GWAS.GITP2.blues.mlmm$GWAS)
GI.TP2.blues[,c('TP','Trait','model')]<-as.list(str_split_fixed(deparse(substitute(GI.TP2.blues)),"\\.",3)[c(2,1,3)])[c(1,2,3)]

GE_5D.TP2.blues<-Pval(GWAS.GETP2_5D.blues.mlmm$GWAS)
GE_5D.TP2.blues[,c('TP','Trait','model')]<-as.list(str_split_fixed(deparse(substitute(GE_5D.TP2.blues)),"\\.",3)[c(2,1,3)])[c(1,2,3)]
GE_5D.TP2.blues
GI_5D.TP2.blues<-Pval(GWAS.GITP2_5D.blues.mlmm$GWAS)
GI_5D.TP2.blues[,c('TP','Trait','model')]<-as.list(str_split_fixed(deparse(substitute(GI_5D.TP2.blues)),"\\.",3)[c(2,1,3)])[c(1,2,3)]
GWAS.sign.blues<-rbind(GE.TP2.blues,GI.TP2.blues,GE_5D.TP2.blues,GI_5D.TP2.blues)

###BLUPS
GE.TP2.blups<-Pval(GWAS.GETP2.blups.mlmm$GWAS)
GE.TP2.blups[,c('TP','Trait','model')]<-as.list(str_split_fixed(deparse(substitute(GE.TP2.blups)),"\\.",3)[c(2,1,3)])[c(1,2,3)]

GI.TP2.blups<-Pval(GWAS.GITP2.blups.mlmm$GWAS)
GI.TP2.blups[,c('TP','Trait','model')]<-as.list(str_split_fixed(deparse(substitute(GI.TP2.blups)),"\\.",3)[c(2,1,3)])[c(1,2,3)]

GE_5D.TP2.blups<-Pval(GWAS.GETP2_5D.blups.mlmm$GWAS)
GE_5D.TP2.blups[,c('TP','Trait','model')]<-as.list(str_split_fixed(deparse(substitute(GE_5D.TP2.blups)),"\\.",3)[c(2,1,3)])[c(1,2,3)]
GE_5D.TP2.blups
GI_5D.TP2.blups<-Pval(GWAS.GITP2_5D.blups.mlmm$GWAS)
GI_5D.TP2.blups[,c('TP','Trait','model')]<-as.list(str_split_fixed(deparse(substitute(GI_5D.TP2.blups)),"\\.",3)[c(2,1,3)])[c(1,2,3)]
GWAS.sign.blups<-rbind(GE.TP2.blups,GI.TP2.blups,GE_5D.TP2.blups,GI_5D.TP2.blups)

GWAS.sign.TP2<-rbind(GWAS.sign.blues,GWAS.sign.blups)
GWAS.sign.TP2



###
#TP3
GE.TP3.blues<-Pval(GWAS.GETP3.blues.mlmm$GWAS)
GE.TP3.blues[,c('TP','Trait','model')]<-as.list(str_split_fixed(deparse(substitute(GE.TP3.blues)),"\\.",3)[c(2,1,3)])[c(1,2,3)]

GI.TP3.blues<-Pval(GWAS.GITP3.blues.mlmm$GWAS)
GI.TP3.blues[,c('TP','Trait','model')]<-as.list(str_split_fixed(deparse(substitute(GI.TP3.blues)),"\\.",3)[c(2,1,3)])[c(1,2,3)]

GE_5D.TP3.blues<-Pval(GWAS.GETP3.blues_5D.mlmm$GWAS)
GE_5D.TP3.blues[,c('TP','Trait','model')]<-as.list(str_split_fixed(deparse(substitute(GE_5D.TP3.blues)),"\\.",3)[c(2,1,3)])[c(1,2,3)]
GE_5D.TP3.blues
GI_5D.TP3.blues<-Pval(GWAS.GITP3_5D.blues.mlmm$GWAS)
GI_5D.TP3.blues[,c('TP','Trait','model')]<-as.list(str_split_fixed(deparse(substitute(GI_5D.TP3.blues)),"\\.",3)[c(2,1,3)])[c(1,2,3)]
GWAS.sign.blues<-rbind(GE.TP3.blues,GI.TP3.blues,GE_5D.TP3.blues,GI_5D.TP3.blues)

###BLUPS
GE.TP3.blups<-Pval(GWAS.GETP3.blups.mlmm$GWAS)
GE.TP3.blups[,c('TP','Trait','model')]<-as.list(str_split_fixed(deparse(substitute(GE.TP3.blups)),"\\.",3)[c(2,1,3)])[c(1,2,3)]

GI.TP3.blups<-Pval(GWAS.GITP3.blups.mlmm$GWAS)
GI.TP3.blups[,c('TP','Trait','model')]<-as.list(str_split_fixed(deparse(substitute(GI.TP3.blups)),"\\.",3)[c(2,1,3)])[c(1,2,3)]

GE_5D.TP3.blups<-Pval(GWAS.GETP3_5D.blups.mlmm$GWAS)
GE_5D.TP3.blups[,c('TP','Trait','model')]<-as.list(str_split_fixed(deparse(substitute(GE_5D.TP3.blups)),"\\.",3)[c(2,1,3)])[c(1,2,3)]
GE_5D.TP3.blups
GI_5D.TP3.blups<-Pval(GWAS.GITP3_5D.blups.mlmm$GWAS)
GI_5D.TP3.blups[,c('TP','Trait','model')]<-as.list(str_split_fixed(deparse(substitute(GI_5D.TP3.blups)),"\\.",3)[c(2,1,3)])[c(1,2,3)]
GWAS.sign.blups<-rbind(GE.TP3.blups,GI.TP3.blups,GE_5D.TP3.blups,GI_5D.TP3.blups)

GWAS.sign.TP3<-rbind(GWAS.sign.blues,GWAS.sign.blups)
GWAS.sign.TP3


#TP4
GE.TP4.blues<-Pval(GWAS.GETP4.blues.mlmm$GWAS)
GE.TP4.blues[,c('TP','Trait','model')]<-as.list(str_split_fixed(deparse(substitute(GE.TP4.blues)),"\\.",3)[c(2,1,3)])[c(1,2,3)]

GI.TP4.blues<-Pval(GWAS.GITP4.blues.mlmm$GWAS)
GI.TP4.blues[,c('TP','Trait','model')]<-as.list(str_split_fixed(deparse(substitute(GI.TP4.blues)),"\\.",3)[c(2,1,3)])[c(1,2,3)]

GE_5D.TP4.blues<-Pval(GWAS.GETP4.blues_5D.mlmm$GWAS)
GE_5D.TP4.blues[,c('TP','Trait','model')]<-as.list(str_split_fixed(deparse(substitute(GE_5D.TP4.blues)),"\\.",3)[c(2,1,3)])[c(1,2,3)]
GE_5D.TP4.blues
GI_5D.TP4.blues<-Pval(GWAS.GITP4_5D.blues.mlmm$GWAS)
GI_5D.TP4.blues[,c('TP','Trait','model')]<-as.list(str_split_fixed(deparse(substitute(GI_5D.TP4.blues)),"\\.",3)[c(2,1,3)])[c(1,2,3)]
GWAS.sign.blues<-rbind(GE.TP4.blues,GI.TP4.blues,GE_5D.TP4.blues,GI_5D.TP4.blues)

###BLUPS
GE.TP4.blups<-Pval(GWAS.GETP4.blups.mlmm$GWAS)
GE.TP4.blups[,c('TP','Trait','model')]<-as.list(str_split_fixed(deparse(substitute(GE.TP4.blups)),"\\.",3)[c(2,1,3)])[c(1,2,3)]

GI.TP4.blups<-Pval(GWAS.GITP4.blups.mlmm$GWAS)
GI.TP4.blups[,c('TP','Trait','model')]<-as.list(str_split_fixed(deparse(substitute(GI.TP4.blups)),"\\.",3)[c(2,1,3)])[c(1,2,3)]
GWAS.GETP4.blups_5D.mlmm
GE_5D.TP4.blups<-Pval(GWAS.GETP4.blups_5D.mlmm$GWAS)
GE_5D.TP4.blups[,c('TP','Trait','model')]<-as.list(str_split_fixed(deparse(substitute(GE_5D.TP4.blups)),"\\.",3)[c(2,1,3)])[c(1,2,3)]
GE_5D.TP4.blups
GI_5D.TP4.blups<-Pval(GWAS.GITP4_5D.blups.mlmm$GWAS)
GI_5D.TP4.blups[,c('TP','Trait','model')]<-as.list(str_split_fixed(deparse(substitute(GI_5D.TP4.blups)),"\\.",3)[c(2,1,3)])[c(1,2,3)]
GWAS.sign.blups<-rbind(GE.TP4.blups,GI.TP4.blups,GE_5D.TP4.blups,GI_5D.TP4.blups)

GWAS.sign.TP4<-rbind(GWAS.sign.blues,GWAS.sign.blups)
GWAS.sign.TP4
#TP5

GE.TP5.blues<-Pval(GWAS.GETP5.blues.mlmm$GWAS)
GE.TP5.blues[,c('TP','Trait','model')]<-as.list(str_split_fixed(deparse(substitute(GE.TP5.blues)),"\\.",3)[c(2,1,3)])[c(1,2,3)]

GI.TP5.blues<-Pval(GWAS.GITP5.blues.mlmm$GWAS)
GI.TP5.blues[,c('TP','Trait','model')]<-as.list(str_split_fixed(deparse(substitute(GI.TP5.blues)),"\\.",3)[c(2,1,3)])[c(1,2,3)]

GE_5D.TP5.blues<-Pval(GWAS.GETP5.blues_5D.mlmm$GWAS)
GE_5D.TP5.blues[,c('TP','Trait','model')]<-as.list(str_split_fixed(deparse(substitute(GE_5D.TP5.blues)),"\\.",3)[c(2,1,3)])[c(1,2,3)]
GE_5D.TP5.blues
GI_5D.TP5.blues<-Pval(GWAS.GITP5_5D.blues.mlmm$GWAS)
GI_5D.TP5.blues[,c('TP','Trait','model')]<-as.list(str_split_fixed(deparse(substitute(GI_5D.TP5.blues)),"\\.",3)[c(2,1,3)])[c(1,2,3)]
GWAS.sign.blues<-rbind(GE.TP5.blues,GI.TP5.blues,GE_5D.TP5.blues,GI_5D.TP5.blues)

###BLUPS
GE.TP5.blups<-Pval(GWAS.GETP5.blups.mlmm$GWAS)
GE.TP5.blups[,c('TP','Trait','model')]<-as.list(str_split_fixed(deparse(substitute(GE.TP5.blups)),"\\.",3)[c(2,1,3)])[c(1,2,3)]

GI.TP5.blups<-Pval(GWAS.GITP5.blups.mlmm$GWAS)
GI.TP5.blups[,c('TP','Trait','model')]<-as.list(str_split_fixed(deparse(substitute(GI.TP5.blups)),"\\.",3)[c(2,1,3)])[c(1,2,3)]

GE_5D.TP5.blups<-Pval(GWAS.GETP5.blups_5D.mlmm$GWAS)
GE_5D.TP5.blups[,c('TP','Trait','model')]<-as.list(str_split_fixed(deparse(substitute(GE_5D.TP5.blups)),"\\.",3)[c(2,1,3)])[c(1,2,3)]
GE_5D.TP5.blups
GI_5D.TP5.blups<-Pval(GWAS.GITP5_5D.blups.mlmm$GWAS)
GI_5D.TP5.blups[,c('TP','Trait','model')]<-as.list(str_split_fixed(deparse(substitute(GI_5D.TP5.blups)),"\\.",3)[c(2,1,3)])[c(1,2,3)]
GWAS.sign.blups<-rbind(GE.TP5.blups,GI.TP5.blups,GE_5D.TP5.blups,GI_5D.TP5.blups)

GWAS.sign.TP5<-rbind(GWAS.sign.blues,GWAS.sign.blups)
GWAS.sign.TP5
















#merge all
GWAS.sign.TP_all<-rbind(GWAS.sign.TP1,GWAS.sign.TP2,GWAS.sign.TP3,GWAS.sign.TP4,GWAS.sign.TP5)
GWAS.sign.TP_all

Pval_Field<-function(i,sig=0){
    i<-i$GWAS
    sign<-0.05/(nrow(i)-sig)
    sign
  i<-i[i$P.value<sign,]
  i$TP="Field"
  i$Trait=NA
  i$model=NA
  return(i)
  
}

phs.blues<-Pval_Field(PHS.blues.mlmm)
phs.blues[,c('Trait','model')]<-as.list(str_split_fixed(deparse(substitute(phs.blues)),"\\.",2)[c(1,2)])[c(1,2)]
phs.blups<-Pval_Field(PHS.blups.mlmm)
phs.blups[,c('Trait','model')]<-as.list(str_split_fixed(deparse(substitute(phs.blups)),"\\.",2)[c(1,2)])[c(1,2)]

scald.blues<-Pval_Field(GWAS.scald.blues.mlmm)
scald.blues[,c('Trait','model')]<-as.list(str_split_fixed(deparse(substitute(scald.blues)),"\\.",2)[c(1,2)])[c(1,2)]

scald.blups<-Pval_Field(GWAS.scald.blups.mlmm,sig=13000)
scald.blups[,c('Trait','model')]<-as.list(str_split_fixed(deparse(substitute(scald.blups)),"\\.",2)[c(1,2)])[c(1,2)]

HD.blues<-Pval_Field(GWAS.HD.blues.mlmm)
HD.blues[,c('Trait','model')]<-as.list(str_split_fixed(deparse(substitute(HD.blues)),"\\.",2)[c(1,2)])[c(1,2)]
HD.blups<-Pval_Field(GWAS.HD.blups.mlmm)
HD.blups[,c('Trait','model')]<-as.list(str_split_fixed(deparse(substitute(HD.blups)),"\\.",2)[c(1,2)])[c(1,2)]

wh.blues<-Pval_Field(GWAS.wh.blues.mlmm,sig=14100)
wh.blues[,c('Trait','model')]<-as.list(str_split_fixed(deparse(substitute(wh.blues)),"\\.",2)[c(1,2)])[c(1,2)]
wh.blups<-Pval_Field(GWAS.wh.blups.mlmm)
wh.blups[,c('Trait','model')]<-as.list(str_split_fixed(deparse(substitute(wh.blups)),"\\.",2)[c(1,2)])[c(1,2)]

Ht.blues<-Pval_Field(GWAS.Ht.blues.mlmm,sig=13900)

Ht.blues[,c('Trait','model')]<-as.list(str_split_fixed(deparse(substitute(Ht.blues)),"\\.",2)[c(1,2)])[c(1,2)]
Ht.blups<-Pval_Field(GWAS.Ht.blups.mlmm)
Ht.blups[,c('Trait','model')]<-as.list(str_split_fixed(deparse(substitute(Ht.blups)),"\\.",2)[c(1,2)])[c(1,2)]
PM.blues<-Pval_Field(GWAS.PM.blues.mlmm,sig=14050)

PM.blues[,c('Trait','model')]<-as.list(str_split_fixed(deparse(substitute(PM.blues)),"\\.",2)[c(1,2)])[c(1,2)]
PM.blups<-Pval_Field(GWAS.PM.blups.mlmm,sig=13900)
PM.blups[,c('Trait','model')]<-as.list(str_split_fixed(deparse(substitute(PM.blups)),"\\.",2)[c(1,2)])[c(1,2)]

Field_sign<-rbind(phs.blues,phs.blups,scald.blues,HD.blues,HD.blups,Ht.blups)


```

```{r}
getwd()
setwd("C:/Users/Karl/git/BarleyGermination-KK")

save(GWAS.sign.TP_all,file="data/GWAS.TP.hits2.Rdata")
save(Field_sign,file="data/GWAS.Field.hits2.Rdata")
#save(GWAS.sign.TP_all,file="data/Genotype_data/GWAS.TP.hits.csv")
#save(Field_sign,file="data/Genotype_data/GWAS.Field.hits.csv")

```