---
title: "Interpreting WDH GWA results"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

Workflow:
Winter_DH_data_consolidation.Rmd ->analysis_script.R->WDH_GenotypeData_Processing.Rmd->GWA WDH Barley.Rmd->GWA_results_interpretation.Rmd

read in GWA results data
```{r}
dir1<-"C:/Users/Karl/git/BarleyGermination-KK"
setwd(dir1)
#the set wd is only for this chunk which should be fine once data is read in
library(here)

#load(here("WMB DH 2020 all data for analysis.RData"))
load(here("data/GWA_results/GWA_WDH_field_phenotypes.Rdata"))
load(here("data/GWA_results/GWA_WDH_TP1.RData"))
load(here("data/GWA_results/GWA_WDH_TP2.RData"))
load(here("data/GWA_results/GWA_WDH_TP3.RData"))
load(here("data/GWA_results/GWA_WDH_TP4.RData"))
load(here("data/GWA_results/GWA_WDH_TP5.RData"))
load(here("data/GWA_results/GWA_WDH_phs.Rdata"))
#please see GWA WDH Barley for model names
library(ggplot2)
```




```{r}
mahatoutput<-function(df,title){

my_title <- paste(paste(title))
df<-df$GWAS[with(df$GWAS, order(Chromosome, Position)),]
nCHR <- length(unique(df$Chromosome))
#df[is.na(df$Chromosome),]$Chromosome
df$BPcum <- NA
s <- 0
nbp <- c()
for (i in unique(df$Chromosome)){
  nbp[i] <- max(df[df$Chromosome == i,]$Position)
  df[df$Chromosome == i,"BPcum"] <- df[df$Chromosome == i,"Position"] + s
  s <- s + nbp[i]
}
axis.set <- df%>% 
  group_by(Chromosome) %>% 
  summarize(center = (max(BPcum) + min(BPcum)) / 2)
ylim <- abs(floor(log10(min(df$P.value)))) + 2 
#str(axis.set)
sig <- 5e-8/13143
manoutput<-ggplot(df, aes(x =BPcum, y = -log10(P.value), 
                                 color = as.factor(Chromosome), size = -log10(0.05))) +
  geom_point(alpha = 0.75) +
  geom_hline(yintercept = -log10(0.05/nrow(df)), color = "red", linetype = "solid") + 
  scale_x_continuous(label = axis.set$Chromosome, breaks = axis.set$center) +
  scale_y_continuous(expand = c(0,0), limits = c(0, ylim)) +
  scale_color_manual(values = rep(c("#276FBF", "#183059"),4)) +
  scale_size_continuous(range = c(0,2)) +
  theme(plot.title = element_text(hjust=1)) +
  
  ggtitle(my_title)+
  labs(x = NULL, 
       y = NULL) + 
  theme_minimal() +
  theme( 
    legend.position = "none",
    panel.border = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    axis.text.x = element_text(angle = 90, size = 8, vjust = 0.5)
  )
return(manoutput)
}
mahatoutput_na<-function(df,title){


my_title <- paste(paste(title))
df<-df$GWAS[with(df$GWAS, order(Chromosome, Position)),]

nCHR <- length(unique(df$Chromosome))

df[is.na(df$Chromosome),]$Chromosome<-"8"
df<-df[!is.na(df$Position),]
df<-df[with(df,order(Chromosome,Position)),]
df$BPcum <- NA
s <- 0
nbp <- c()
for (i in unique(df$Chromosome)){
  nbp[i] <- max(df[df$Chromosome == i,]$Position)
  df[df$Chromosome == i,"BPcum"] <- df[df$Chromosome == i,"Position"] + s
  s <- s + nbp[i]
}
axis.set <- df%>% 
  group_by(Chromosome) %>% 
  summarize(center = (max(BPcum) + min(BPcum)) / 2)
ylim <- abs(floor(log10(min(df$P.value)))) + 2 
#str(axis.set)
sig <- 5e-8/13143
manoutput<-ggplot(df, aes(x =BPcum, y = -log10(P.value), 
                                 color = as.factor(Chromosome), size = -log10(0.05))) +
  geom_point(alpha = 0.75) +
  geom_hline(yintercept = -log10(0.05/nrow(df)), color = "red", linetype = "solid") + 
  scale_x_continuous(label = axis.set$Chromosome, breaks = axis.set$center) +
  scale_y_continuous(expand = c(0,0), limits = c(0, ylim)) +
  scale_color_manual(values = rep(c("#276FBF", "#183059"),4)) +
  scale_size_continuous(range = c(0,2)) +
  theme(plot.title = element_text(hjust=1)) +
  
  ggtitle(my_title)+
  labs(x = NULL, 
       y = NULL) + 
  theme_minimal() +
  theme( 
    legend.position = "none",
    panel.border = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    axis.text.x = element_text(angle = 90, size = 8, vjust = 0.5)
  )
return(manoutput)
}

mahatoutput(GWAS.GETP1.blues.mlmm,"GE BLUES TP1")
mahatoutput(GWAS.GETP1.blups.mlmm,"GE BLUPS TP1")
mahatoutput(GWAS.GETP2.blups.mlmm,"GE BLUPS TP2")
#ManGEP1.fe<-homeMadeManhattan30K(GWAS.GETP1.blues.mlmm$GWAS[c(2,3)],)



```
Chromosome
````{r}
#code for max min of Chromosomes
#####
Chr_Max_min<-c()
Chr_Max_min$Chr<-NA
Chr_Max_min$min<-NA
Chr_Max_min$max<-NA
Chr_Max_min<-as.data.frame(Chr_Max_min)
Chr_Max_min[1,1:3]<-c("1H",min(TP1GE.fe[TP1GE.fe$Chromosome==1,]$Position),max(TP1GE.fe[TP1GE.fe$Chromosome==1,]$Position))
Chr_Max_min[2,1:3]<-c("2H",min(TP1GE.fe[TP1GE.fe$Chromosome==2,]$Position),max(TP1GE.fe[TP1GE.fe$Chromosome==2,]$Position))
Chr_Max_min[3,1:3]<-c("3H",min(TP1GE.fe[TP1GE.fe$Chromosome==3,]$Position),max(TP1GE.fe[TP1GE.fe$Chromosome==3,]$Position))
Chr_Max_min[4,1:3]<-c("4H",min(TP1GE.fe[TP1GE.fe$Chromosome==4,]$Position),max(TP1GE.fe[TP1GE.fe$Chromosome==4,]$Position))
Chr_Max_min[5,1:3]<-c("5H",min(TP1GE.fe[TP1GE.fe$Chromosome==5,]$Position),max(TP1GE.fe[TP1GE.fe$Chromosome==5,]$Position))
Chr_Max_min[6,1:3]<-c("6H",min(TP1GE.fe[TP1GE.fe$Chromosome==6,]$Position),max(TP1GE.fe[TP1GE.fe$Chromosome==6,]$Position))
Chr_Max_min[7,1:3]<-c("7H",min(TP1GE.fe[TP1GE.fe$Chromosome==7,]$Position),max(TP1GE.fe[TP1GE.fe$Chromosome==7,]$Position))
Chr_Max_min[8,1:3]<-c("UN",min(TP1GE.fe[TP1GE.fe$Chromosome==8,]$Position),max(TP1GE.fe[TP1GE.fe$Chromosome==8,]$Position))
#####                 
Chr_Max_min$Total<-NA
Chr_Max_min[1:8,4]<-table(TP1GE.fe$Chromosome)
Chr_Max_min
TP1GE.fe[['P.value']]
```


P-val TP1
```{r}

pval<-function(df,sig,name){
  cutoff<-sig
pval_list<-df$GWAS[df$GWAS[,4]<cutoff,]
pval_list$Population<-NA
pval_list$Population<-as.character(name)
pval_list
}
GETP1.fe.p<-pval(GWAS.GETP1.blues.mlmm,sig,"GETP1 Fixed")
GETP1.re.p<-pval(GWAS.GETP1.blups.mlmm,sig,"GETP1 Random")
GITP1.fe.p<-pval(GWAS.GITP1.blues.mlmm,sig,"GITP1 Fixed")
GITP1.re.p<-pval(GWAS.GITP1.blups.mlmm,sig,"GITP1 Random")

TP1.p<-rbind(GETP1.fe.p,GETP1.re.p,GITP1.fe.p,GITP1.re.p)
TP1.p
```
```{r}


GETP1.fe<-mahatoutput(GWAS.GETP1.blues.mlmm,"TP1 GE BLUES")
GETP1.re<-mahatoutput(GWAS.GETP1.blups.mlmm,"TP1 GE BLUPs")
GETP1.fe
GITP1.fe<-mahatoutput(GWAS.GITP1.blues.mlmm,"GI TP1 BLUEs")
GITP1.re<-mahatoutput(GWAS.GITP1.blups.mlmm,"GI TP1 BLUPS")
getwd()

png("plots/Update/GWAS TP1 3 Day.png",width = 447, height = 346)

ggarrange(GETP1.fe, GETP1.re, GITP1.fe, GITP1.re, 
          ncol = 2, nrow = 2)
dev.off()
####

GETP1_5D.fe<-mahatoutput(GWAS.GETP1_5D.blues.mlmm,"TP1 5 Day GE BLUES")
GETP1_5D.re<-mahatoutput(GWAS.GETP1_5D.blups.mlmm,"TP1 5 Day GE BLUPS")
GITP1_5D.fe<-mahatoutput(GWAS.GITP1_5D.blues.mlmm,"TP1 5 Day GI BLUES")
GITP1_5D.re<-mahatoutput(GWAS.GITP1_5D.blups.mlmm,"TP1 5 Day GI BLUPS")

png("plots/Update/GWAS TP1 5 Day.png",width = 447, height = 346)
ggarrange(GETP1_5D.fe, GETP1_5D.re, GITP1_5D.fe, GITP1_5D.re, ncol = 2, nrow = 2)
dev.off()

GETP1_5D.fe.p<-pval(GWAS.GETP1_5D.blues.mlmm,sig,"GETP1 5 Day Fixed")
GETP1_5D.re.p<-pval(GWAS.GETP1_5D.blups.mlmm,sig,"GETP1 5 Day Random")
GITP1_5D.fe.p<-pval(GWAS.GITP1_5D.blues.mlmm,sig,"GITP1 5 Day Fixed")
GITP1_5D.re.p<-pval(GWAS.GITP1_5D.blups.mlmm,sig,"GITP1 5 Day Random")

TP1_5D.p<-rbind(GETP1_5D.fe.p,GETP1_5D.re.p,GITP1_5D.fe.p,GITP1_5D.re.p)
TP1_5D.p


## Timepoint 2 ###
GETP2.fe<-mahatoutput(GWAS.GETP2.blues.mlmm,"GE TP2 BLUPS")
GETP2.re<-mahatoutput(GWAS.GETP2.blups.mlmm,"GE TP2 BLUPS")
GITP2.fe<-mahatoutput(GWAS.GITP2.blues.mlmm,"GI TP2 BLUES")
GITP2.re<-mahatoutput(GWAS.GITP2.blups.mlmm,"GI TP2 BLUPS")





#something is wrong with this one
GITP2.re<-mahatoutput(GWAS.GITP2.blups.mlmm)
#GITP2.fe had to remove it
GETP2.fe<-mahatoutput(GWAS.GETP2.blues.mlmm,"GE TP2 BLUPS")
GETP2.re<-mahatoutput(GWAS.GETP2.blups.mlmm,"GE TP2 BLUPS")
GITP2.fe<-mahatoutput(GWAS.GITP2.blues.mlmm,"GI TP2 BLUES")
GITP2.re<-mahatoutput(GWAS.GITP2.blups.mlmm,"GI TP2 BLUPS")

png("plots/Update/GWAS TP2 3 Day.png",width = 447, height = 346)
ggarrange(GETP2.fe, GETP2.re,GITP2.fe, GITP2.re,
          
          ncol = 2, nrow = 2)
dev.off()




GETP2_5D.fe<-mahatoutput(GWAS.GETP2_5D.blues.mlmm,"TP2 5 Day GE BLUES")
GETP2_5D.re<-mahatoutput(GWAS.GETP2_5D.blups.mlmm,"TP2 5 Day GE BLUPS")
GITP2_5D.fe<-mahatoutput(GWAS.GITP2_5D.blues.mlmm,"TP2 5 Day GI BLUES")
GITP2_5D.re<-mahatoutput(GWAS.GITP2_5D.blups.mlmm,"TP2 5 Day GI BLUPS")

png("plots/Update/GWAS TP2 5 Day.png",width = 447, height = 346)
ggarrange(GETP2_5D.fe, GETP2_5D.re, GITP2_5D.fe, GITP2_5D.re, 
          
          ncol = 2, nrow = 2)
dev.off()

GETP2.fe.p<-pval(GWAS.GETP2.blues.mlmm,sig,"GETP2 Fixed")
GETP2.re.p<-pval(GWAS.GETP2.blups.mlmm,sig,"GETP2 Random")
GITP2.fe.p<-pval(GWAS.GITP2.blues.mlmm,sig,"GITP2 Fixed")
GITP2.fe.p<-GITP2.fe.p[GITP2.fe.p$P.value<0.05/13143,]
GITP2.fe.p<-GITP2.fe.p[,c(1:6)]
GITP2.fe.p$effect<-NA
GITP2.fe.p$Population<-NA
GITP2.fe.p$Population<-"GITP2 Fixed"
GITP2.re.p<-pval(GWAS.GITP2.blups.mlmm,sig,"GITP2 Random")

colnames(GITP2.fe.p)[3]<-"Position"
colnames(GITP2.re.p)
TP2.p<-rbind(GETP2.fe.p,GETP2.re.p,GITP2.fe.p,GITP2.re.p)
TP2.p

GETP2_5D.fe.p<-pval(GWAS.GETP2_5D.blues.mlmm,sig,"GETP2 5 Day Fixed")
GETP2_5D.re.p<-pval(GWAS.GETP2_5D.blups.mlmm,sig,"GETP2 5 Day Random")
GITP2_5D.fe.p<-pval(GWAS.GITP2_5D.blues.mlmm,sig,"GITP2 5 Day Fixed")
GITP2_5D.re.p<-pval(GWAS.GITP2_5D.blups.mlmm,sig,"GITP2 5 Day Random")

TP2_5D.p<-rbind(GETP2_5D.fe.p,GETP2_5D.re.p,GITP2_5D.fe.p,GITP2_5D.re.p)
TP2_5D.p
##
## Timepoint 3 ###
GWAS.GITP3.blups.mlmm$GWAS[is.na(GWAS.GITP3.blups.mlmm$GWAS)]
GWAS.GITP3.blups.mlmm$GWAS

GETP3.fe<-mahatoutput(GWAS.GETP3.blues.mlmm,"GE TP3 BLUES")
GETP3.re<-mahatoutput(GWAS.GETP3.blups.mlmm,"GE TP3 BLUPS")
GITP3.fe<-mahatoutput(GWAS.GITP3.blues.mlmm,"GI TP3 BLUES")
GITP3.re<-mahatoutput_na(GWAS.GITP3.blups.mlmm,"GI TP3 BLUPS")


GETP3_5D.fe<-mahatoutput(GWAS.GETP3.blues_5D.mlmm,"TP3 5 Day GE BLUES")
GETP3_5D.re<-mahatoutput(GWAS.GETP3_5D.blups.mlmm,"TP3 5 Day GE BLUPS")
GITP3_5D.fe<-mahatoutput(GWAS.GITP3_5D.blues.mlmm,"TP3 5 Day GI BLUES")
GITP3_5D.re<-mahatoutput(GWAS.GITP3_5D.blups.mlmm,"TP3 5 Day GI BLUPS")

png("plots/Update/GWAS TP3 3 Day.png",width = 447, height = 346)
ggarrange(GETP3.fe, GETP3.re,GITP3.fe, GITP3.re, 
                   ncol = 2, nrow = 2)

dev.off()
png("plots/Update/GWAS TP3 5 Day.png",width = 447, height = 346)

ggarrange(GETP3_5D.fe, GETP3_5D.re, GITP3_5D.fe, GITP3_5D.re, 
                    ncol = 2, nrow = 2)
dev.off()
###
GETP3.fe.p<-pval(GWAS.GETP3.blues.mlmm,sig,"GETP3 Fixed")
GETP3.re.p<-pval(GWAS.GETP3.blups.mlmm,sig,"GETP3 Random")
GITP3.fe.p<-pval(GWAS.GITP3.blues.mlmm,sig,"GITP3 Fixed")
GITP3.re.p<-pval(GWAS.GITP3.blups.mlmm,sig,"GITP3 Random")

TP3.p<-rbind(GETP3.fe.p,GETP3.re.p,GITP3.fe.p,GITP3.re.p)
TP3.p

GETP3_5D.fe.p<-pval(GWAS.GETP3.blues_5D.mlmm,sig,"GETP3 5 Day Fixed")
GETP3_5D.re.p<-pval(GWAS.GETP3_5D.blups.mlmm,sig,"GETP3 5 Day Random")
GITP3_5D.fe.p<-pval(GWAS.GITP3_5D.blues.mlmm,sig,"GITP3 5 Day Fixed")
GITP3_5D.re.p<-pval(GWAS.GITP3_5D.blups.mlmm,sig,"GITP3 5 Day Random")

TP3_5D.p<-rbind(GETP3_5D.fe.p,GETP3_5D.re.p,GITP3_5D.fe.p,GITP3_5D.re.p)
TP3_5D.p

## Timepoint 4 ###
GETP4.fe<-mahatoutput(GWAS.GETP4.blues.mlmm,"GE TP4 BLUES")
GETP4.re<-mahatoutput(GWAS.GETP4.blups.mlmm,"GE TP4 BLUPS")
GITP4.fe<-mahatoutput(GWAS.GITP4.blues.mlmm,"GI TP4 BLUES")
GITP4.re<-mahatoutput(GWAS.GITP4.blups.mlmm,"GI TP4 BLUPS")

GWAS.GETP4.blups_5D.mlmm
GETP4_5D.fe<-mahatoutput(GWAS.GETP4.blues_5D.mlmm,"TP4 5 Day GE BLUES")
GETP4_5D.re<-mahatoutput(GWAS.GETP4.blups_5D.mlmm,"TP4 5 Day GE BLUPS")
GITP4_5D.fe<-mahatoutput(GWAS.GITP4_5D.blues.mlmm,"TP4 5 Day GI BLUES")
GITP4_5D.re<-mahatoutput(GWAS.GITP4_5D.blups.mlmm,"TP4 5 Day GI BLUPS")
#GITP3.fe had to remove it

png("plots/Update/GWAS TP4 3 Day.png",width = 447, height = 346)
ggarrange(GETP4.fe, GETP4.re,GITP4.fe, GITP4.re, 
         
          ncol = 2, nrow = 2)

dev.off()
png("plots/Update/GWAS TP4 5 Day.png",width = 447, height = 346)
ggarrange(GETP4_5D.fe, GETP4_5D.re, GITP4_5D.fe, GITP4_5D.re, 
         
          ncol = 2, nrow = 2)
dev.off()
GETP4.fe.p<-pval(GWAS.GETP4.blues.mlmm,sig,"GETP4 Fixed")
GETP4.re.p<-pval(GWAS.GETP4.blups.mlmm,sig,"GETP4 Random")
GITP4.fe.p<-pval(GWAS.GITP4.blues.mlmm,sig,"GITP4 Fixed")
GITP4.re.p<-pval(GWAS.GITP4.blups.mlmm,sig,"GITP4 Random")

TP4.p<-rbind(GETP4.fe.p,GETP4.re.p,GITP4.fe.p,GITP4.re.p)
TP4.p
GWAS.GETP4.blups_5D.mlmm
GETP4_5D.fe.p<-pval(GWAS.GETP4.blues_5D.mlmm,sig,"GETP4 5 Day Fixed")
GETP4_5D.re.p<-pval(GWAS.GETP4.blups_5D.mlmm,sig,"GETP4 5 Day Random")
#none 
GITP4_5D.fe.p<-pval(GWAS.GITP4_5D.blues.mlmm,sig,"GITP4 5 Day Fixed")
GITP4_5D.re.p<-pval(GWAS.GITP4_5D.blups.mlmm,sig,"GITP4 5 Day Random")

TP4_5D.p<-rbind(GETP4_5D.fe.p,GITP4_5D.fe.p,GITP4_5D.re.p)
TP4_5D.p
#Timepoint 5

GETP5.fe<-mahatoutput(GWAS.GETP5.blues.mlmm,"GE TP5 BLUES")
GETP5.re<-mahatoutput(GWAS.GETP5.blups.mlmm,"GE TP5 BLUPS")
GITP5.fe<-mahatoutput(GWAS.GITP5.blues.mlmm,"GI TP5 BLUES")
GITP5.re<-mahatoutput(GWAS.GITP5.blups.mlmm,"GI TP5 BLUPS")

GWAS.GETP5.blups_5D.mlmm
GETP5_5D.fe<-mahatoutput(GWAS.GETP5.blues_5D.mlmm,"TP5 5 Day GE BLUES")
GETP5_5D.re<-mahatoutput(GWAS.GETP5.blups_5D.mlmm,"TP5 5 Day GE BLUPS")
GITP5_5D.fe<-mahatoutput(GWAS.GITP5_5D.blues.mlmm,"TP5 5 Day GI BLUES")
GITP5_5D.re<-mahatoutput(GWAS.GITP5_5D.blups.mlmm,"TP5 5 Day GI BLUPS")
#GITP3.fe had to remove it
png("plots/Update/GWAS TP5 3 Day.png",width = 447, height = 346)
ggarrange(GETP5.fe, GETP5.re,GITP5.fe, GITP5.re, 
         
          ncol = 2, nrow = 2)

dev.off()

png("plots/Update/GWAS TP5 5 Day.png",width = 447, height = 346)
ggarrange(GETP5_5D.fe, GETP5_5D.re, GITP5_5D.fe, GITP5_5D.re, 
         
          ncol = 2, nrow = 2)


dev.off()




#Field
HD.fe<-mahatoutput(GWAS.HD.blues.mlmm)
HD.re<-mahatoutput(GWAS.HD.blues.mlmm)
wh.fe<-mahatoutput(GWAS.wh.blues.mlmm)
wh.re<-mahatoutput(GWAS.wh.blups.mlmm)

ggarrange(HD.fe, HD.re, wh.fe, wh.re, 
          labels = c("HD FE", "HD RE", "WH FE","WH RE"),hjust = -1.2,vjust = 1,
          ncol = 2, nrow = 2)

Ht.fe<-mahatoutput(GWAS.Ht.blues.mlmm)
Ht.re<-mahatoutput(GWAS.Ht.blups.mlmm)
PM.fe<-mahatoutput(GWAS.PM.blues.mlmm)
PM.re<-mahatoutput(GWAS.PM.blues.mlmm)

ggarrange(HD.fe, HD.re, wh.fe, wh.re, 
          labels = c("Ht FE", "Ht RE", "PhysM FE","PhysM RE"),hjust = -1.2,vjust = 1,
          ncol = 2, nrow = 2)

Scald.fe<-mahatoutput(GWAS.scald.blues.mlmm)
Scald.re<-mahatoutput(GWAS.scald.blups.mlmm)
PHS.fe<-mahatoutput(PHS.blues.mlmm)
PHS.re<-mahatoutput(PHS.blups.mlmm)

ggarrange(Scald.fe, Scald.re, PHS.fe, PHS.re, 
          labels = c("Scald FE", "Scald RE", "PHS FE","PHS RE"),hjust = -1.2,vjust = 1,
          ncol = 2, nrow = 2)

WH.fe.p<-pval(GWAS.wh.blues.mlmm,sig,"Field WinterH Fixed")
#none
WH.re.p<-pval(GWAS.wh.blups.mlmm,sig,"Field WinterH Random")
HD.fe.p<-pval(GWAS.HD.blues.mlmm,sig,"Field Heading date Fixed")
HD.re.p<-pval(GWAS.HD.blups.mlmm,sig,"Field Heading date Random")

Ht.fe.p<-pval(GWAS.Ht.blues.mlmm,sig,"Field Height Fixed")
#none
Ht.re.p<-pval(GWAS.Ht.blups.mlmm,sig,"Field Height Random")
PM.fe.p<-pval(GWAS.PM.blues.mlmm,sig,"Field PhysM Fixed")
PM.re.p<-pval(GWAS.PM.blups.mlmm,sig,"Field PhysM Random")
PHS.fe.p<-pval(PHS.blues.mlmm,sig,"Field PHS Fixed")
#none
PHS.re.p<-pval(PHS.blups.mlmm,sig,"Field PHS Random")
#none
Field.p<-rbind(WH.re.p,HD.fe.p,HD.re.p,Ht.re.p,PM.fe.p,PM.re.p)

Total_markers<-rbind(TP1.p,TP2.p,TP3.p,TP4.p,Field.p)
write.csv(Total_markers,"data/GWA_results/Significant_markers.csv")
View(Total_markers)
```
