---
title: "Haplotype_analysis"
author: "Karl Kunze"
date: "2/9/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---
read in phenotypes
```{r}
load(here("data/Winter_DH/TP1_WDH20_BLUE_all.RData"))
load(here("data/Winter_DH/TP2_WDH20_BLUE_all.RData"))
load(here("data/Winter_DH/TP3_WDH20_BLUE_all.RData"))
load(here("data/Winter_DH/TP4_WDH20_BLUE_all.RData"))
load(here("data/Winter_DH/TP5_WDH20_BLUE_all.RData"))
load(here("data/Winter_DH/Field_WDH20_BLUE_all.Rdata"))

load(here("data/Winter_DH/TP1_WDH20_BLUP_all.RData"))
load(here("data/Winter_DH/TP2_WDH20_BLUP_all.RData"))
load(here("data/Winter_DH/TP3_WDH20_BLUP_all.RData"))
load(here("data/Winter_DH/TP4_WDH20_BLUP_all.RData"))
load(here("data/Winter_DH/TP5_WDH20_BLUP_all.RData"))
load(here("data/Winter_DH/Field_WDH20_BLUP_all.Rdata"))

load(here("data/Winter_DH/WMB DH 2020 all data for analysis.RData"))


```
read in Genotypes
```{r}
load(here("data/Genotype_data/myGD20.Rdata"))
load(here("data/Genotype_data/myGM20.Rdata"))


```

LD heatmap
```{r}

library(LDcorSV)
library(ggplot2)
library(reshape2)
grep("JHI-Hv50k-2016-312217", colnames(myGD20))

grep("JHI-Hv50k-2016-312121", colnames(myGD20))

#grep("JHI-Hv50k-2016-312094", colnames(myGD20))


grep("JHI-Hv50k-2016-316817", colnames(myGD20))
grep("JHI-Hv50k-2016-316934", colnames(myGD20))
grep("Qsd1", colnames(myGD20))

myGD20$Qsd1


colnames(myGD20)
library(LD.Measures)
ld_heatmap=function(df){
  ld <- as.matrix(round(df,0))
  
  if(c(-1,3,4) %in% ld){
    ld[which(ld==3)]=2
    ld[which(ld==4)]=2
    ld[which(ld== -1)]=0
  }
  
  LD <- LD.Measures(donnees=ld,  na.presence=F)
  #LD$loc1=as.character(LD$loc1); LD$loc2=as.character(LD$loc2)
  r2 <- matrix(0, nrow=ncol(df), ncol=ncol(df))
  r2[lower.tri(r2, diag=FALSE)] <- LD$r2
  r2 <- t(r2)
  r2 <- as.data.frame(round(r2, 5))
  diag(r2) <- 1
  r2[lower.tri(r2)] = NA
  rownames(r2)=colnames(df); colnames(r2)=rownames(r2)
  r_2=melt(as.matrix(r2), na.rm=T)
  
  graphic = ggplot(r_2, aes(Var2, Var1, fill = value))+
    geom_tile(color = "white")+
    scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
                       midpoint = 0.5, limit = c(0,1), space = "Lab", name="r2") +
    theme_classic() #+    ggtitle(paste("LD r2 from",colnames(r2)[1],"-", colnames(r2)[length(colnames(r2))], sep=" " ))
  return(graphic)
}

#to remove the marker labels on each axis, use theme_void() instead of theme_classic()
#test of some random markers
ld_heatmap(myGD20[,c(8750:8752,9043:9052)])
###

ld_heatmap(myGD20[,c(8750:8752,9043:9052)]) + ggtitle('LD between significant marker regions at 5H') +
  theme(axis.text.x = element_text(angle = 90))+
  
opts(axis.title.x = theme_text(vjust=-2))+
  scale_x_discrete(label = c("Qsd1","312217","312121","316817","316934"), breaks = c("Qsd1","JHI-Hv50k-2016-312217","JHI-Hv50k-2016-312121","JHI-Hv50k-2016-316817","JHI-Hv50k-2016-316934"))+
  scale_y_discrete(label = c("Qsd1","JHI-Hv50k-2016-312217","JHI-Hv50k-2016-312121","JHI-Hv50k-2016-316817","JHI-Hv50k-2016-316934"), breaks = c("Qsd1","JHI-Hv50k-2016-312217","JHI-Hv50k-2016-312121","JHI-Hv50k-2016-316817","JHI-Hv50k-2016-316934"))+ 
  xlab(NULL)+ylab(NULL)


```


Qsd Haplotype 
```{r}
TP_all_WDH20_BLUE_all<-rbind(TP1_WDH20_BLUE_all,TP2_WDH20_BLUE_all,TP3_WDH20_BLUE_all,TP4_WDH20_BLUE_all,TP5_WDH20_BLUE_all)
TP_all_WDH20_BLUE_all$Pedigree<-All_pheno_TPall$Pedigree[match(TP_all_WDH20_BLUE_all$taxa,All_pheno_TPall$Entry)]

Qsd1<-myGD20[,c('taxa','Qsd1')]
TP_all_WDH20_BLUE_all[,c(8)]
Qsd_haplotype<-merge(TP_all_WDH20_BLUE_all[,c(1:5,8)],Qsd1,by='taxa',all.x = TRUE)


table(Qsd_haplotype[!Qsd_haplotype$Qsd1=="0" & !Qsd_haplotype$Qsd1=="2",]$Qsd1)
Qsd_haplotype<-Qsd_haplotype[!is.na(Qsd_haplotype$Qsd1),]
Qsd_haplotype$Qsd1<-as.factor(Qsd_haplotype$Qsd1)
colnames(Qsd_haplotype)
Qsd_haplotype


Qsd_GE=melt(Qsd_haplotype, id.vars =c("taxa","TP","Qsd1"), measure.vars = c("GE"))
ggplot(data=Qsd_GE, aes(x=TP, y=value,color=Qsd1)) +
  geom_boxplot()+
  #facet_grid(cols=vars(dataset), scales="free", rows=vars(variable)) +
  theme_bw() + 
  ggtitle("Fixed Effect GE Haplotype WDH")+
  scale_fill_manual(values=c("#cccccc", "#636363")) +
  
  xlab("Qsd Haplotype") + ylab("BLUE GE") 

Qsd_GI=melt(Qsd_haplotype, id.vars =c("taxa","TP","Qsd1"), measure.vars = c("GIscale"))
ggplot(data=Qsd_GI, aes(x=TP, y=value,color=Qsd1)) +
  geom_boxplot()+
  #facet_grid(cols=vars(dataset), scales="free", rows=vars(variable)) +
  theme_bw() + 
  ggtitle("Fixed effect GI Qsd1 haplotype WDH")+
  scale_fill_manual(values=c("#cccccc", "#636363")) +
  
  xlab("Qsd Haplotype") + ylab("BLUE GI Scale") 



```