---
title: "Winter_DH_Germination_barley_analysis"
author: "Karl Kunze"
date: "10/26/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---
Workflow:
Winter_DH_data_consolidation.Rmd ->analysis_script.R->WDH_GenotypeData_Processing.Rmd

reading in files
```{r}
path<-"C:/Users/Karl/git/BarleyGermination-KK"
setwd(path)
getwd()
library(dplyr)
rm(list = ls(all = TRUE))
library(stringr);library(plyr);library(dplyr)



```

## Timeponts for 2020
```{r}
#time point 1, remember that we only did half of the population

TP1_half<-as.data.frame(read.csv("data/Phenotype_Data/2020/DHtp1_full_F.csv",stringsAsFactors = FALSE))%>%dplyr::select(Entry,PLOT,Full_sample,Sample_ID,replication,Day1Germ,Day2Germ,Day3Germ,Day4Germ,Day5Germ,kernels_remaining,Year,Location)%>%arrange(Sample_ID,replication)%>%dplyr::mutate(PLOT=replace(PLOT,PLOT=="SN",13001),PLOT=replace(PLOT,PLOT=="SR",13002),PLOT=as.numeric(PLOT))%>%arrange(PLOT)%>%mutate(TP="TP1",PM_date=5)
TP1_half$PLOT

#Time point 2
TP2<-as.data.frame(read.csv("data/Phenotype_Data/2020/DHtp2_all_F.csv",stringsAsFactors = FALSE))%>%dplyr::select(Entry,PLOT,Full_sample,Sample_ID,replication,Day1Germ,Day2Germ,Day3Germ,Day4Germ,Day5Germ,kernels_remaining,Year,Location)%>%arrange(Sample_ID,replication)%>%dplyr::mutate(PLOT = gsub("a","",PLOT),PLOT=replace(PLOT,PLOT=="SN",13001),PLOT=replace(PLOT,PLOT=="SR",13002),PLOT=as.numeric(PLOT))%>%arrange(PLOT)%>%mutate(TP="TP2",PM_date=19)
TP2$PLOT
#Timepoint 3

TP3<-as.data.frame(read.csv("data/Phenotype_Data/2020/DHtp3_all_F.csv",stringsAsFactors = FALSE))%>%dplyr::select(Entry,PLOT,Full_sample,Sample_ID,replication,Day1Germ,Day2Germ,Day3Germ,Day4Germ,Day5Germ,kernels_remaining,Year,Location)%>%arrange(Sample_ID,replication)%>%dplyr::mutate(PLOT = gsub("a","",PLOT),PLOT=replace(PLOT,PLOT=="SN",13001),PLOT=replace(PLOT,PLOT=="SR",13002),PLOT=as.numeric(PLOT))%>%arrange(PLOT)%>%mutate(TP="TP3",PM_date=47)
#Timepoint 4
TP4<-as.data.frame(read.csv("data/Phenotype_Data/2020/DHtp4_all_combined_F.csv",stringsAsFactors = FALSE))%>%dplyr::select(Entry,PLOT,Full_sample,Sample_ID,replication,Day1Germ,Day2Germ,Day3Germ,Day4Germ,Day5Germ,kernels_remaining,Year,Location)%>%arrange(Sample_ID,replication)%>%dplyr::mutate(PLOT = gsub("a","",PLOT),PLOT=replace(PLOT,str_detect(PLOT,"SN-"),13001),PLOT=replace(PLOT,str_detect(PLOT,"SR-"),13002),PLOT=as.numeric(PLOT))%>%arrange(PLOT)%>%mutate(TP="TP4",PM_date=96)
#Timepoint 5 
TP5<-as.data.frame(read.csv("data/Phenotype_Data/2020/TP5_all.csv",stringsAsFactors = FALSE))%>%dplyr::select(Entry,PLOT,Full_sample,Sample_ID,replication,Day1Germ,Day2Germ,Day3Germ,Day4Germ,Day5Germ,kernels_remaining,Year,Location)%>%arrange(Sample_ID,replication)%>%dplyr::mutate(PLOT = gsub("a","",PLOT),PLOT=replace(PLOT,str_detect(PLOT,"SN-"),13001),PLOT=replace(PLOT,str_detect(PLOT,"SR-"),13002),PLOT=as.numeric(PLOT))%>%arrange(PLOT)%>%mutate(TP="TP5",PM_date=152)
#rbind the different timepoints, arrange by plot, rep, timepoint, replace location names and add the GE/GI calculations. Year is already included


TP2020=rbind(TP1_half,TP2,TP3,TP4,TP5)%>%arrange(PLOT,replication,TP)%>%
    mutate(Location=replace(Location,str_detect(Location,"Ketola"),values="Ketola2020"),Location=replace(Location,str_detect(Location,"Snyder"),"Snyder2020"))%>%
    mutate(GE =(Day1Germ+Day2Germ+Day3Germ)/(Day1Germ+Day2Germ+Day3Germ+Day4Germ+Day5Germ+kernels_remaining),
         GI = 10*GE*(Day1Germ+Day2Germ+Day3Germ)/(Day1Germ+2*Day2Germ+3*Day3Germ),
         GI = ifelse(is.nan(GI),0,GI),
         GE5 = (Day1Germ+Day2Germ+Day3Germ+Day4Germ+Day5Germ)/(Day1Germ+Day2Germ+Day3Germ+Day4Germ+Day5Germ+kernels_remaining),
         GI5 = 10*GE5*(Day1Germ+Day2Germ+Day3Germ+Day4Germ+Day5Germ)/(Day1Germ+Day2Germ*2+Day3Germ*3+Day4Germ*4+Day5Germ*5))%>%
 mutate(Check=ifelse(!grepl("BS",Entry), 1, 0),
              taxa0 = mapvalues(Entry, from = c('Check 1','Check 2','Check 3','Check 4','Check 5','Check 6'),to = c('Flavia', 'Scala','DH130910','SY_Tepee','Wintmalt','Charles')),
                taxa =  mapvalues(taxa0, from = c("Check 1-Flavia","Check 2-Scala","Check 3-DH130910","Check 3-SY Tepee","Check 4-SY Tepee","Check 5-Wintmalt","Check 6-Charles"),
                to = c('Flavia', 'Scala','DH130910','SY_Tepee','SY_Tepee','Wintmalt','Charles')),
         taxa = gsub(pattern = '-',replacement = '_',taxa),
         taxa = gsub(pattern = ' ', replacement = '_',taxa),
         Family = mapvalues(substr(taxa,1,3), from = c('BS6','BS7','BS8','BS9','DH1','Fla','SY_','Sca','Win','KWS'), 
                            to = c('Flavia/DH130910','Scala/DH130910','SY_Tepee/DH130910','Wintmalt/DH130910',
                                   'DH130910','Flavia/DH130910','SY_Tepee/DH130910','Scala/DH130910','Wintmalt/DH130910','Scala/DH130910')))%>%dplyr::select(-taxa0)%>%mutate(Year=as.factor(Year))
                
colnames(TP2020)
TP2020$PLOT
library(readxl)
#phs data


#detach("package:plyr", unload=TRUE)

DH_2020_PHS<-as.data.frame(read.csv("data/Winter_DH/WMB_DH_2020_Ketola_PHS.csv",stringsAsFactors = TRUE))%>%dplyr::rename(sprout_score=Sprout.Score)%>%dplyr::select(Entry,PLOT,sprout_score)%>%mutate(sprout_score=as.character(sprout_score),sprout_score=replace(sprout_score,sprout_score=="0","00000"))%>%na.omit()%>%arrange(PLOT)


DH_2020_PHS=DH_2020_PHS%>%mutate(taxa =  mapvalues(Entry, from = c("Check 1-Flavia","Check 2-Scala","Check 3-DH130910","Check 3-DH130911","Check 4-SY Tepee","Check 5-Wintmalt","Check 6-Charles"),
                to = c('Flavia', 'Scala','DH130910','DH130910','SY_Tepee','Wintmalt','Charles')),
 
         taxa = gsub(pattern = ' ', replacement = '_',taxa))%>%dplyr::select(-Entry)

five_avg=function(df,pheno,new_pheno,missing_phenos=F){
  df[[pheno]]=as.numeric(df[[pheno]])
  df <- cbind(df, "ID" = outer(df[[pheno]], 10^c(4:0), function(a, b) a %/% b %% 10))
  if(missing_phenos==T){
    df$ID.1[which(df$note=="*")]=NA
  }
  df$new_pheno=apply(df[,c((ncol(df)-4):ncol(df))],1,function(x) mean(x, na.rm=T))
  df$new_pheno=as.numeric(df$new_pheno)
  # df$var=as.numeric(apply(df[,c((ncol(df)-4):ncol(df))], 1,var))
  #df$sd=as.numeric(apply(df[,c((ncol(df)-5):(ncol(df)-1))], 1,function(x) sd(x, na.rm=T)))
  #df=df[,c(1:(ncol(df)-9),(ncol(df)-2),(ncol(df)-1), ncol(df))]

}
DH_2020_PHS$phs=five_avg(df=DH_2020_PHS,pheno='sprout_score',new_pheno='phs')

#field data
DH_2020_Snyder<-as.data.frame(read_excel("data/Winter_DH/WMB_DH_2020_kkGit.xlsx",sheet = "Snyder"))
DH_2020_Ketola<-as.data.frame(read_excel("data/Winter_DH/WMB_DH_2020_kkGit.xlsx",sheet = "Ketola"))
#detach("package:plyr", unload=TRUE) c#can add dplyr:: in front of function instead
DH_2020_Snyder$Entry
DH_2020_field<-rbind(DH_2020_Snyder,DH_2020_Ketola)%>%dplyr::filter(!Entry=="Check 7-Erie")%>%dplyr::select(Entry,PLOT,mass,Facultative_Greenhouse,Facultative_Spring_planted,wh_percent,Scald,HD,Ht,PM)%>%dplyr::rename(fac_GH=Facultative_Greenhouse,fac_field=Facultative_Spring_planted,ws_percent=wh_percent,scald=Scald,Maturity_date=PM)%>%mutate(scald=as.numeric(scald),HD=as.numeric(HD),Ht=as.numeric(Ht),Maturity_date=as.numeric(Maturity_date),Year="year")%>%mutate(fac_field=replace(fac_field,str_detect(fac_field,"W"),"Winter"),fac_field=na_if(fac_field,"Missing"))


DH_2020_field$Entry
#this the map function for Greenhouse scored facultative
DH_2020_field=DH_2020_field%>%mutate(fac_GH=mapvalues(fac_GH,from=c("F","H","H?","H1","MP","N","N?","W"),to=c("Fac","Fac","Winter","Winter","Winter","Winter","Winter","Winter")))%>%mutate(taxa =  mapvalues(Entry, from = c("Check 1-Flavia","Check 2-Scala","Check 3-DH130910","Check 3-DH130911","Check 4-SY Tepee","Check 4-Sy Tepee","Check 5-Wintmalt","Check 6-Charles"),
                to = c('Flavia', 'Scala','DH130910','DH130910','SY_Tepee',"SY_Tepee",'Wintmalt','Charles')),
 
         taxa = gsub(pattern = ' ', replacement = '_',taxa))%>%dplyr::select(-Entry)

julian_days=function(df, cutoff){
  may=31+29+31+30
  june=may+31
  #july=june+30
  
  s=which(df$HD<cutoff)
  a=which(df$HD>cutoff)
  df$HD[a]=df$HD[a]+may
  df$HD[s]=df$HD[s]+june
  df$HD
  
}
DH_2020_field$HD<-julian_days(DH_2020_field,26)

colnames(DH_2020_field)[!colnames(DH_2020_field)%in%colnames(DH_2020_PHS)]
colnames(DH_2020_PHS)[!colnames(DH_2020_PHS)%in%colnames(DH_2020_field)]
#ensure that PLOT then taxa column names match, and no others do

DH_2020_field_traits=dplyr::full_join(DH_2020_field,DH_2020_PHS,by=c("PLOT","taxa"))

DH_2020_field_traits<-DH_2020_field_traits%>%mutate(Year="2020",Family = mapvalues(substr(taxa,1,3), from = c('BS6','BS7','BS8','BS9','DH1','Fla','SY_','Sca','Win','KWS','Cha'), 
                            to = c('Flavia/DH130910','Scala/DH130910','SY_Tepee/DH130910','Wintmalt/DH130910',
                                   'DH130910','Flavia/DH130910','SY_Tepee/DH130910','Scala/DH130910','Wintmalt/DH130910','Scala/DH130910','Charles')))
colnames(TP2020)[colnames(TP2020)%in%names(DH_2020_field_traits)]
colnames(DH_2020_field_traits)[colnames(DH_2020_field_traits)%in%names(TP2020)]
colnames(TP2020)
#Doing a left join with the germination traits here, only keeping the germination related lines
table(TP2020$PLOT)
All2020<-dplyr::left_join(TP2020,DH_2020_field_traits,by=c("PLOT","taxa","Family","Year"))
DH2020_field_trait_names=colnames(DH_2020_field_traits)
All2020=All2020%>%dplyr::rename(SourcePLOT=PLOT,seed_mass=mass,HD_date=HD,AssayNumber=Sample_ID)%>%dplyr::select(-sprout_score,-Entry)
#need to create a pivot longer df for field traits, 



```
## 2021 data Timepoint
```{r}

DHs2021 = rbind(read_excel('data/Phenotype_Data/2021/DHs_GGS_TP1_PM5_full.xlsx') %>% mutate(notes = NA, TP = 'TP1'),
                read_excel('data/Phenotype_Data/2021/DHs_PM_12_full.xlsx')%>% mutate(notes = NA,TP = 'TP1.5'),
                read_excel('data/Phenotype_Data/2021/DHs_PM_19_GGS_TP2_full.xlsx') %>% mutate(notes = NA, TP = 'TP2'),
                read_excel('data/Phenotype_Data/2021/DHs_PM_33_GGS_TP3_full.xlsx') %>% mutate(TP = 'TP2.5'),
                read_excel('data/Phenotype_Data/2021/DHs_PM_47_GGS_TP4_full.xlsx') %>% mutate(TP = 'TP3'),
                read_excel('data/Phenotype_Data/2021/DHs_PM_68_GGS_TP5_full.xlsx')%>% mutate(TP='TP3.5'),
                read_excel('data/Phenotype_Data/2021/DHs_PM_96_full.xlsx') %>% mutate(TP = 'TP4'),
                read_excel('data/Phenotype_Data/2021/DHs_PM_150_GGS_TP7_full.xlsx') %>% mutate(Pmdate = 152,notes = NA,TP = 'TP5')) %>%
  filter(!is.na(Day2Germ)) %>% filter(AssayNumber != 10 & AssayNumber != 318 & AssayNumber != 190) %>% #These look to be contamination
  filter(Location == 'McGowan' | Location == 'Ketola') %>%
  dplyr::select(!c('seed_mass', 'GerminationAssay','notes')) %>%
  dplyr::mutate(GE =(Day1Germ+Day2Germ+Day3Germ)/(Day1Germ+Day2Germ+Day3Germ+Day4Germ+KernelsLeft),
         GI = 10*GE*(Day1Germ+Day2Germ+Day3Germ)/(Day1Germ+2*Day2Germ+3*Day3Germ), Rep = as.factor(Rep)) %>%
  dplyr::rename('taxa' = Entry, 'PM_date' = Pmdate, 'rep' = Rep,kernels_remaining=KernelsLeft)  %>%
  plyr::mutate(Family = mapvalues(substr(taxa,1,3), from = c('BS6','BS7','BS8','BS9','DH1','Fla','SY_','KWS','Win'), 
                            to = c('Flavia/DH130910','Scala/DH130910','SY_Tepee/DH130910','Wintmalt/DH130910',
                                   'DH130910','Flavia/DH130910','SY_Tepee/DH130910','Scala/DH130910','Wintmalt/DH130910')),
         GI = ifelse(is.nan(GI),0,GI), 
         taxa = ifelse(AssayNumber == 408, 'Charles',taxa)) %>%#AssayNumber 408 is 'Charles' not the entry it claims to be!
        # taxa = gsub(pattern = '-',replacement = '_',taxa), 
      mutate(   taxa = gsub(pattern = 'KWS Scala', replacement = 'Scala',taxa),
         taxa = ifelse(taxa == 'KWS_Scala','Scala',taxa),
          Check=ifelse(!grepl("BS",taxa), 1, 0),
          AssayNumber=as.numeric(AssayNumber),SourcePLOT=as.numeric(SourcePLOT))%>%arrange(SourcePLOT)
#just to check non experimental lines present in this
#DHs2021 %>% filter(substr(taxa,1,2) !='BS') %>% select(taxa) %>% unique()
colnames(DHs2021)
```
Field Phenotypes 2021
```{r}
getwd()
load("data/Phenotype_Data/2021/field/WBMaster21_all.Rdata")

#detach("package:plyr", unload=TRUE)
WBMaster21=WBMaster21%>%dplyr::rename(test_wt="Test Wt",SourcePLOT=PLOT21,grain_name="GRAIN NAME",ws_percent=ws,PowderyMildew="PoweryMildew")%>%dplyr::select(Entry,SourcePLOT,Location,Year,Check,Row,Column,kgha,ws_percent,frost_damage,HD_date,TP_date,Maturity_date,Ht,Lodging,phs,Scald,SB,PowderyMildew)%>%
 mutate(HD_date=as.numeric(format(WBMaster21$HD_date, "%j")),TP_date=as.numeric(format(WBMaster21$TP_date,"%j")))%>%mutate(taxa=gsub("KWS Scala","Scala",Entry))%>%dplyr::rename(TipPoint_date=TP_date)%>%dplyr::select(-Entry)
str(WBMaster2)
WBMaster21$Check<-as.factor(WBMaster21$Check)
summary(lm(phs~taxa+Location+Location:Check,data=WBMaster21))$coefficients
summary(lm(phs~taxa+Location+Location:Check,data=WBMaster21))$coefficients[1,1]

table1<-summary(lm(phs~taxa+Location+Location:Check,data=WBMaster21))$coefficients[,1]
table1=as.data.frame(table1+summary(lm(phs~taxa+Location+Location:Check,data=WBMaster21))$coefficients[1,1])
#View(table1)
colnames(table1)<-c("effect","taxa")
table1$taxa<-rownames(table1)
table1[table1$effect>4,]
phs=WBMaster21%>%dplyr::select(taxa,phs)%>%group_by(taxa)%>%summarize(mean = mean(phs))%>%ungroup()
str(phs)


table(table1>2)
table(phs$mean>2)
418/434
table(table1>=2&table1<4)
16/434
table(table1>=4)
8/434
colnames(WBMaster21)[names(WBMaster21)%in%names(DHs2021)]
colnames(DHs2021)[names(DHs2021)%in%names(WBMaster21)]
#doing a merge, will be performing a left join merge with the Germ traits first. For this study we're not interested in lines that were not assayed for germination and/or malting quality
table(DHs2021$SourcePLOT)

WBMaster21_trait_names=colnames(WBMaster21)
str(WBMaster21$Check)
str(DHs2021$Check)
DHs2021$Check<-as.factor(DHs2021$Check)
All2021=dplyr::left_join(DHs2021,WBMaster21,by=c("SourcePLOT","taxa","Check","Location","Year"))
#All_pheno_TPall=merge(DH_2020_field,TPall,by=c("PLOT","Entry","Location","Year"),all =TRUE)
#doing an rbind
All2021=All2021%>%dplyr::rename(replication=rep,scald=Scald,spot_bloch=SB)%>%dplyr::select(-PM)
colnames(All2021)[!names(All2021)%in%names(All2020)]
colnames(All2020)[names(All2020)%in%names(All2021)]

#detach("package:plyr", unload=TRUE)
#library(plyr)
DH2020_2021=rbind.fill(All2020,All2021)%>%arrange(Year,SourcePLOT)

DH2020_2021=DH2020_2021%>%mutate(replication=as.factor(replication),Year=as.factor(Year),PM_date=as.factor(PM_date))
```
# data quality control
```{r}

DH2020_2021%>% group_by(Year,PM_date) %>% ggplot(aes(GE)) + 
        # it sets bins intead of breaks, so add 1
        geom_histogram(bins = 15) + 
        # make a new "facet" for each value of `variable` (formerly column names), and 
        # use a convenient x-scale instead of the same for all 3
        facet_wrap(~Year+PM_date, scales = 'free_x')+ggtitle(lab="Histogram for Germination Energy")+theme_bw()
DH2020_2021%>% group_by(Year) %>% ggplot(aes(PM_date,GI,group=taxa)) + 
        # it sets bins intead of breaks, so add 1
       geom_smooth()+
        # make a new "facet" for each value of `variable` (formerly column names), and 
        # use a convenient x-scale instead of the same for all 3
        facet_wrap(~Year, scales = 'free_x')+theme_bw()

```

```{r}
TP_data_test=DH2020_2021%>%dplyr::select(taxa,SourcePLOT,Location,Family,Year,replication,PM_date,GE,GI,GE5,GI5,Day1Germ)%>% dplyr::select(-replication)%>%pivot_wider(names_from = c(PM_date), values_from = -names(.)[c(1:6)],values_fill=NA,values_fn =mean)
```
#plotting residuals
```{r}
#plot(lm(GI~ taxa +Location+replication, DH2020_2021%>% filter(DH2020_2021$Year=="2020",DH2020_2021$PM_date ==5)))

#plot(lm(GI~ taxa +Location+replication, DH2020_2021%>% filter(DH2020_2021$Year=="2020",DH2020_2021$PM_date ==19)))
#Location significant
#plot(lm(GI~ taxa +Location+replication, DH2020_2021%>% filter(DH2020_2021$Year=="2020",DH2020_2021$PM_date ==47)))
#Location significant
#plot(lm(GI~ taxa +Location+replication, DH2020_2021%>% filter(DH2020_2021$Year=="2020",DH2020_2021$PM_date ==96)))
#replication significant
#plot(lm(GI~ taxa +Location+replication, DH2020_2021%>% filter(DH2020_2021$Year=="2020",DH2020_2021$PM_date ==152)))
#all significant
#DH 2020 GE
#plot(lm(GE~ taxa +Location+replication, DH2020_2021%>% filter(DH2020_2021$Year=="2020",DH2020_2021$PM_date ==5)))
#Location
#plot(lm(GE~ taxa +Location+replication, DH2020_2021%>% filter(DH2020_2021$Year=="2020",DH2020_2021$PM_date ==19)))
#Location significant
#plot(lm(GE~ taxa +Location+replication, DH2020_2021%>% filter(DH2020_2021$Year=="2020",DH2020_2021$PM_date ==47)))
#Location significant and rep
#test<-lm(GE~scald+ taxa +Location+replication, DH2020_2021%>% filter(DH2020_2021$Year=="2020",DH2020_2021$PM_date ==96))
summary(test)
#DH2020_2021%>% filter(DH2020_2021$Year=="2020",DH2020_2021$PM_date ==96)

DH2020_2021%>%filter(Year=="2020",PM_date%in%c("47","96","152"))%>% ggplot(aes(PM_date,GE,group=taxa)) + 
        # it sets bins intead of breaks, so add 1
       geom_smooth(na.rm = TRUE,se=FALSE)
        # make a new "facet" for each value of `variable` (formerly column names), and 
        # use a convenient x-scale instead of the same for all 3
    #    facet_wrap(~Year, scales = 'free_x')+theme_bw()

#the GE values descending should most likely be removed
ttt<-DH2020_2021%>%filter(Year=="2020",PM_date%in%c("47","96","152"))

removal_2020_GE_GI<-ttt[ttt$PM_date=="152"&ttt$GE<0.85&!is.na(ttt$SourcePLOT),]$SourcePLOT%>%unique()


#location and rep significant
#plot(lm(GE~ taxa +Location+replication, DH2020_2021%>% filter(DH2020_2021$Year=="2020",DH2020_2021$PM_date ==152)))
#data modifications for 2020
#remove outliers at later timepoints, my guess is that the seed was bad, it was sourced from a poor part of the Snyder field
removal_2020_GE_GI


DH2020_2021=DH2020_2021%>%filter(!SourcePLOT%in%c(removal_2020_GE_GI))
```
## 2021
```{r}
DH2020_2021$Family
yu<-TP_data_test%>%filter(Year=="2021")%>%droplevels()%>%drop_na(GE_152,GE_96)
yu$delta_1<-yu$GE_152-yu$GE_96
yu%>%filter(delta_1<=-0.15)





yu2<-TP_data%>%filter(Year=="2021")%>%droplevels()%>%drop_na(GE_47,GE_33)
yu$delta_1<-yu$GE_47-yu$GE_33
yu%>%filter(delta_1<=-0.3)
#found 3, filter based on source plot
remove_2021<-c("7127","7293","7394")
DH2020_2021=DH2020_2021%>%filter(!SourcePLOT%in%c(remove_2021))
DH2020_2021%>%filter(Year=="2021")%>% ggplot(aes(PM_date,GE,group=SourcePLOT,color=Check)) + 
        # it sets bins intead of breaks, so add 1
       geom_smooth(na.rm = TRUE,se=FALSE)
        # make a new "facet" for each value of `variable` (formerly column names), and 
        # use a convenient x-scale instead of the same for all 3
      #facet_wrap(, scales = 'free_x')+theme_bw()

```

```{r}
TP_data=DH2020_2021%>%dplyr::select(taxa,SourcePLOT,Location,Family,Year,replication,PM_date,GE,GI,GE5,GI5,Day1Germ)%>% dplyr::select(-replication)%>%pivot_wider(names_from = c(PM_date), values_from = -names(.)[c(1:6)],values_fill=NA,values_fn =mean)

```

## joining with field data
```{r}

#TP-data from earlier




traits<-c(DH2020_field_trait_names,WBMaster21_trait_names)
traits
traits=traits[-c(1,2,7,12,30,31)]



field_data=DH2020_2021%>%dplyr::select(all_of(traits))%>%distinct()
```

```{r}
#going to rename DH130910 here
TP_data[TP_data$taxa=="DH130910",]$taxa<-"Lightning"
field_data[field_data$taxa=="DH130910",]$taxa<-"Lightning"
TP_data[TP_data$taxa=="SY_Tepee",]$taxa<-"Tepee"
field_data[field_data$taxa=="SY_Tepee",]$taxa<-"Tepee"
TP_data$taxa
DH2020_2021_wide<-full_join(field_data,TP_data,by=c("SourcePLOT","taxa","Family","Location","Year"))

save(DH2020_2021, file="data/WMB_DH_Germination_data2020_2021.RData")#DH2020_2021
save(DH2020_2021_wide, file="data/WMB_DH_Germination_data2020_2021_wide_format.RData")#DH2020_2021_wide
```


