---
title: "The SD1 seed dormancy locus influence of pre-harvest sprouting resistance and seed dormancy loss over time"
author:
  - name: Karl Kunze
    orcid: 0000-0003-4548-1808
    email: khk44@cornell.edu
    affiliations:
      - name: Cornell University
        address: 422 Bradfield Hall
        city: Ithaca
        state: NY
        postal-code: 14853
  - name: Mark Sorrells
    email: khk44@cornell.edu
    affiliations:
      - name: Cornell University
        address: 240 Emerson Hall
        city: Ithaca
        state: NY
        postal-code: 14853
address:
  - code: Cornell University
    address: Plant Breeding and Genetics, Bradfield Hall, Ithaca, NY 14853
editor: visual
format:
  docx:
    reference-doc: custom-reference-doc.docx
link-citations: true
editor_options: 
  chunk_output_type: console
crossref:
  fig-title: Figure    # (default is "Figure")
  tbl-title: tbl     # (default is "Table")
  title-delim: —     
bibliography: references.bib
---

```{r, include=FALSE}
library(flextable)
library(officer)
library(officedown)
library(dplyr)
library(tidyr)
library(knitr)
library(png)


sysname <- Sys.info()["sysname"]
sysname
if(sysname == "Darwin") {
    path<-("~/Google Drive/projectX") # example on mac machine
} else if(sysname == "Linux") {
    path<-("/home/karl/git/naked_barley_GWAS") # example on linux machine
} else if(sysname == "Windows") {
    path<-("C:/Users/kars8/git/naked_barley_GWAS") # example on win machine
}
path
quarto_path<-paste0(path,"/ms")
setwd(quarto_path)
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE)

```

# Abstract

# Introduction

Barley(*Hordeum vulagare L*) is grown worldwide for food consumption, animal feed and malt for brewing and distilling. A significant portion of barley acreage in United States and Canada is grown for malting and distilling purposes due to the high premiums compared to animal feed and food consumption. Winter malting barley, where the barley is sown in the fall, is becoming of greater interest to growers, malsters, and brewers. Changes in climate, shifting cropping systems and demand for locally farmed products are pushing the adoption of winter malting barley to be grown in non traditional environments. Growing malting barley in novel environments is challenging, particularly if there is wet and humid conditions during grain fill or at harvest. Selection of malting barley for non traditional enviroments requires a delicate balance to select for grain that does not sprout at harvest but can also provide high quality malt within minimal storage time.

Seed dormancy and pre harvest sprouting(PHS) are critical traits for the production of malting barley. Seed dormancy is defined as the inability of a seed to germinate under favorable conditions [@bewley2013] and developed as an evolutionary mechanism to avoid stress environments. Dormancy in barley is induced during seed development and is influenced by genetic and environmental factors such as temperature, water context, oxygen availability and light[@gubler2005]. Dormancy peaks at physiological maturity(PM) where the last photosynate leaves the grain, and degrades over a period of time after harvest. The rate of dormancy loss varies widely from days to months based on genotype and environmental conditions during grainfill. Prolonged seed dormancy is undesirable for malting as germination is uneven, has low vigor and and is expensive to store for long periods of time. Barley that has little to no dormancy at physiological maturity is prone to pre-harvest sprouting(PHS), where wet and humid conditions induce starch degredation and germination in the field before harvest. PHS can be visible in the form of visible radicle and collectible emergence or in pre germination where starch in the grain begins to degrade. Pregerminated grain is most often usuable for malt or food purposes. Acheiving the balance between PHS resistance and high quality malt is a key breed target for barley breeding.

Genetic sources of PHS resistance and seed dormancy have been well characterized in barley. The large effect QTL loci of SD1 and SD2 on chromosome 5H have been mapped extensively in a wide range of barley germplasm. [@han1996; @ullrich1992quantitative; @linQTLMappingDormancy2009]. Genes have been cloned at each locus: alanine aminotransferase at SD1[*HvAlaT1* @satoAlanineAminotransferaseControls2016] and a mitogen-actived protein kinase kinase 3 at SD2[*HvMKK3* @nakamura2016]. Alleles for both AlaAT and MKK3 have been identified by @vetchMutationsHvMKK3HvAlaAT12020 @sweeneyInteractionsBarleySD12022 @sweeney2022 for spring and winter barley germplasm. The mutation L214F in AlaAT results in a loss of dormancy. ALaAT has been one of the first targets of Cas9-induced mutagenesis in barley @hisano2022 prolonging dormancy in mutant types.

Genome wide associations studies(GWAS) have become the standard practice to identify traits of interest in various types of breeding populations. Numerous GWAS methods are available, and improvement to models that account for population structure @yuGeneticAssociationMapping2006 using principal component analysis @PricePrincipalComponents and the inclusion of kinship and Q matrix allow for mapping association studies to be conducted across structed populations

. Advances in barley marker platforms such as the Illumina barley 50K SNP chip @bayerDevelopmentEvaluationBarley2017 and the development of improved barley reference genomes [@mascherLongreadSequenceAssembly2021] have made for higher resolution mapping of relevant malting barley traits. Increased efficiency of models and computation power have allowed not only for the association of high density marker platforms with large phenotypes, but also the use of single step GWAS modeling. Single step GWAS offers more flexibility with the capacity for the integration of more phenotypic information, inclusion of multiple fixed and random effects, as well as retaining more information that can be lost in two step analyses.

The objectives of this study aimed to genetic characterize pre-harvest sprouting and seed dormancy loss over time in a connected half sib winter malting barley breeding population. Our goals for this research were to a) Identifiy QTL for PHS, seed dormancy and seed dormacy loss over time using GWAS and b) model seed dormancy loss over time to assess optimal selection for seed dormancy. Understanding the genetic basis for PHS, seed dormancy, and seed dormancy loss over time will be invaluable information for breeders to select highly quality malting barley that have PHS resistance while also maintain a short seed dormancy period to ensure high malting quality.

# Methods

## Plant populations

The populations used in study were part of the winter malting barley breeding population at Cornell University. Four bi-parental half sibling populations were developed by crossing a common parent 'Lightning' @hayesRegistrationLightningBarley2021 , a faculative type barley, to four winter malting barley cultivars; 'KWS Scala', 'Flavia', 'SY Tepee' and 'Wintmalt'. Double haploids were developed from the crosses at Oregon state University using anther culture of $F_1$ seed from each cross. After sufficient seed increase, lines were planted in fall 2019 and fall 2020 in two fields each season in Ithaca, NY. Fields in 2019 for the 2020 harvest season,named Snyder and Ketola 5, were planted in a modified augmented design of single 1m rows with all parent lines(5), and check 'Charles' replicated in blocks across the field. The total number of plots for each locations was 544. The ratio of checks to experimental lines was approximately 10%. Approximatley 450 lines were evaluated at both locations. Fields sown in 2020 for the 2021 harvest season, named Ketola 3 and McGowan , were planted according to a randomized 480 plot augmented block design of 3 x 1 meter trimmed plots with parent lines "Lightning" and "KWS Scala" and additional line "Endeavor" used as checks. The ratio of checks to experimental lines was approximately 11%. At McGowan, approximately 25% of the plots were sampled. Data were unbalanced across years and locations due to discard of lines with poor winter survival and partial sampling of McGowan. Approximately 450 lines were phenotyped across the three complete locations with 76, 117, 128 and 124 lines in the Flavia/Lightning, KWS Scala/Lightning, SY Tepee/Lightning and Wintmalt/Lightning families, respectively.

## Field Phenotyping and sampling

Physiological maturity(PM) was recorded as the date when 50% of the of plot lost green color from the peduncle and spike. Two days after PM, bundles of 30-50 selected mature spikes were harvested, dried for 2 days at 38 C, hand threshed, and stored at -20C to pause after ripening. @nagelNovelLociRole2019 The standardization of harvesting and freezing spikes 2 days after the PM of the plot enabled observation of traits at the same number of after-ripening for all lines.

PHS was measured by harvesting 5 spikes per headrow at physiological maturity (PM), after-ripening for 3 days, and then misting in a greenhouse for 3 days, after which the spikes were assessed for PHS on a 0 to 9 scale. Due to labor constraints brought on by the pandemic in the 2020 field season, phenotyping capacity was limited and germination was prioritized for that year. PHS was phenotyped on a sub-sample of 100 lines from one location. The sub-sample consisted of all facultative types across all four families, parental checks, and Charles. For 2021, both preliminary yield trials(480 plots at two locations) were measured for PHS.

For germination measurements in 2020, twelve to fifteen additional spikes were sampled from headrows of 444 lines in two locations two days after 50% of the headrow reached PM for use in germination tests. Some lines were omitted due to poor winter survival and low seed quality. In 2021, fifteen to twenty spikes were sampled from one complete location (480 plots) and approximately 25% at the second location (120 plots). Furthermore, a subset of 240 plots were sampled for an additional 35-40 spikes for malt quality. Of the 240 plots, 120 were selected with shared lines between both locations (60 lines at both locations) and the remaining 120 plots sampled were split evenly based on seed availability after we appropriated amounts for our germination tests.

Spikes were dried for 48 hours before being hand threshed and frozen at -20 C. Grain was removed from the freezer 24 hours prior to starting the assays and stored at ambient lab temperature and humidity for the duration of the experiment. Germination energy (GE) and germination index or rate (GI) were measured at five time points for 2020: 5 (TP1), 19 (TP2), 47 (TP3), 96 (TP4), and 152 (TP5) days post PM. Germination Energy(GE) and germination index or rate (GI) were measured at eight time points for 2021: 5(TP1), 12(TP1.5), 19 (TP2), 33(TP2.5), 47(TP3), 68 (TP3.5), 96 (TP4) and 152(TP5) days post PM. Germination tests followed the American Society of Brewing Chemists (ASBC) method for GE with two modifications. The first modification was the use of 30 kernels instead of 100 kernels. The second modification was an extended germination count from 3 days to 5 days in lieu of counting for 3 days and using H~2~O~2~ to break dormancy. In brief, GE was calculated as the percentage germinated kernels after three days and for five days. GI was calculated as: 

$3 Day GI =10 (N24+N48 +N72)/ (N24+2N48+3N72)$

*5 Day GI =10 (N~24~+N~48~ +N~72~ +N~96~+N~120~)/ (N~24~+2N~48~ +3N~72~+4N~96~ +5N~120~)*

where N~24~, N~48~, N~72~, N~96~ and N~120~ were the number of germinated kernels at 24, 48, 72, 96 and 120 hours after the start of the assay. For analysis GI was scaled by GE as GI~scale~ = GI\*GE to account for low germination at TP1 and TP2.  For TP1 in 2020, a subset of the lines (223) was phenotyped compared to the remaining timepoints (444). The TP1 subsample included for the remaining lines. For sampling in 2022, we only sampled one complete location (480 plots) and 120 plots at the second location. For the second location, 60 of the 120 lines were sampled based on a range of their respective GE and GI rates measured from the previous field season. The remaining 60 samples consisted of sampling check lines and available seed.

In addition to measuring germination, a 120 line subset previously mentioned were sent to the USDA Cereal Crops and research unit(CCRU) in Madison, WI. The small grain samples were frozen upon arrival. Each line was malted in single replicates at two different time points 67 days post PM and 152 post PM, a modification from our original plan of 47/111 days post PM due to substantial observed dormancy at 47 days post PM. Due to limits on how many tea ball samples could be malted at one time, the samples were malted in batches every week for two months. Malting procedure and analysis were performed in the methods described by . We are still waiting on the last batch to be analyzed and aim to write a supplemental report once the complete malting data for the winter barley becomes available. Preliminary results indicate that there was significant dormancy for some lines when the grain was malted at 68 days post PM, given the high beta glucan levels.

                  

We previously reported development of a high-throughput Kompetitive Allele Specific Primer (KASP) marker AlaAT1_L214F for the causal mutation in *HvAlaAT1* discovered by Sato et al. (2016). We also developed KASP assays for a SNP in the 5' UTR of *HvGA20ox1* (GA20ox1_331_5UTR), the E165Q mutation in *HvMKK3* identified in Vetch et al. (2020) for both spring barley and winter barley. A summary of the winter barley haplotypes for the parent lines and checks are found in QTL x environment modeling of malting barley preharvest sprouting (Sweeney et al. 2021). All experimental lines and parent genotypes were monomorphic for dormant HvMKK3. The check lines Charles and Endeavor used as a phs susceptibility check in 2020 and 2021 respectively, have the highly non-dormant (N\*) allele for MKK3 and the dormant AlaAT(D) allele, however we cannot make specific conclusions about this haplotype given the low representation in the winter barley population.

All lines were genotyped with the 50Fk Illumina Infinium iSelect SNP array at the USDA Small Grains Genotyping Lab in Fargo, ND. After filtering poor quality markers, minor allele frequency (MAF) below 0.05, and monomorphic sites, 15,467 polymorphic markers remained and were used for genome-wide association (GWA). After conducting linkage disequilibrium (LD) pruning to reduce high LD blocks that exist in double haploid populations, we retained 8,384 markers for analysis. The *GAPIT* R package (Tang et al., 2016) was used for GWA. Multi-locus mixed models (MLMM) were fit for germination traits at each time point and for PHS. MLMM models have fewer false positive associations and use forward and backward step-wise regression compared to the standard mixed linear model.  P-values below the Bonferroni cutoff (p=0.05) of 3.57x10-6 were considered significant. A summary of the GWA results is presented in Table 1. Models were run for all trait/time point combinations, including the 5-day extensions. In addition to single timepoint GWAS, we used time series analysis to develop models that represent dormancy breakage over time. Details of the methods can be found in Rooney. et. al 2022. Briefly, each line was modelled in a logistic curve representing the GE and rate over time, both with years and combined years. We derived components of the logistic curve, such as time to 95% germination or time to 5.0 GI, to determine what novel loci, if any, can be detected if we use the timepoint data as a complete model compared to conducting GWA on each timepoint independently

# Results

Pre-harvest sprouting

 

For the 2020 year, we only did a subsample of phs scoring. While the 2020 data did follow the trend explained for the 2021 results, we did not have enough observations to determine whether all experimental lines in the 2020 year were resistant or susceptible to phs in the 2020 environment mainly due to low variation and sample size. In our first complete year observation of the 435 unique lines in our trials, we found that 95% of our experimental lines were pre-harvest sprouting resistant (0-2 score) across two locations. Approximately 4.4 % were somewhat resistant (2-4) and only 1.6 % of our lines were PHS susceptible (above 4). The low mean of phs for most of the lines is encouraging, however phs needs to be tested in at least more than one year to account for different environmental effects. This is particularly important given the significant increased dormancy we observed for the 2021 year. Given the low variation of phs scores, correlations were low to most of the GE and GI timepoints. PHS was only moderately correlated with the first timepoint (PM 5) for GE(0.633) and GI(0.683). Even with a week of after ripening, correlation with phs scores dropped significantly at time point 1.5(12 days post PM) for GE(0.367) and GI(0.415). This suggests that for our winter barley population, there is potential to select for increased dormancy break while maintaining PHS resistance. Broad sense heritability for all germination traits, timepoints, years and combinations were very high(0.9). Heritability dropped slight for GE at later time points due to reduced variation but still retained heritability values a minimum\~0.75. 

 

Genome wide association results

For single timepoint GWAS, we found a total of 37 significant marker trait associations associated with GE and GI across all timepoints and years. One marker per LD group of the significant single time point GWA was selected in table 1 to prevent redundancy. Significant marker trait associations from the logistic models were also included. The most significant association was the KASP marker for AlaAT_L214F(Qsd1) and the closely associated 50K JHI-Hv50k-2016-276836(r=0.91) marker. Other potential hits detected in the study include Isoamylase (*HvISA3*,HORVU.MOREX.r2.5HG0404420) which is a starch-debranching enzyme located at 475796690-475807295 bp, 705025 bp distal to marker JHI-Hv50k-2016-311435. Isoamylases hydrolyze α-(1,6) glycosidic linkages and debranch amylopectin during grain filling (Gous and Fox, 2017). Shu and Rasmussen (2014) identified a MTA for amylose content highly associated with the contig MLOC_10776, which includes *HvISA3* (https://ics.hutton.ac.uk/morexGenes/). Starch with higher amylose content is hydrolyzed more slowly by amylolytic enzymes and higher amylose content has been hypothesized to be a contributing factor to grain dormancy (Chu et al., 2014). Although the role of amylose content in seed dormancy has been hypothesized, prior evidence for the role of *HvISA3* is limited. This locus may be useful for PHS resistance but a consistent decrease in GI is not desirable. Negative impacts on starch related malting quality traits like malt extract may also be present.  Another gene of interest in this region is an abscisic acid responsive protein (Liu et al. 2013). Abscisic acid (ABA) is an important regulator of seed dormancy in barley: increases in ABA maintain seed dormancy and decreases in ABA reduce seed dormancy in barley (Gómez-Cadenas et. al 1999). Other potential novel loci include HvVP1 (Viviparous-1) which may be associated with JHI-Hv50k-2016-165725 on chromosome 3H and segregating in the SY Tepee family. HvVP1 is a master transcription factor regulator that controls switching between seed maturation and germination in barley (Abraham et al. 2016).

### Role of alanine amino transferase

Alanine amino transferase played a significant role in dormancy break in our winter malting barley population. Figures 3a-c show germination rate and energy for each family of the population grouped by haplotype for AlaAT over years 2020, 2021, and combined analysis 2020/2021. A check "family" was included for comparison to Charles for 2020 and Endeavor for 2021. Parents Scala, SY Tepee and Wintmalt contained the non-dormant AlaAT allele(N) and the common parent DH130910 and Flavia contained the dormant allele(D). In both years, GE showed clear differentiation over time based on AlaAT haplotype, particularly at time point 2(19 days post PM) for 2020 and timepoints 1.5-3.5(19 days post PM through 68 days post PM). GI showed clear differentiation both across timepoints and within timepoints based on the AlaAT haplotype. The differences in GE and GI for both years based on each haplotype demonstrate that AlaAT significantly affects germination rate, energy and subsequently the rate of dormancy breakage. We also observed significant differences between GE and GI depending on the year. In 2020, dormancy break occurred around time point 3(47 days post PM). In 2021, dormancy break was substantially higher and did not occur until timepoints 3.5(68 days post PM) and 4(96 days post PM). The significant effect of the year environment on dormancy demonstrates the need to test seed germination traits across multiple years.

The observed dormancy for most non dormant haplotypes at earlier post physiological maturity (PM) days is encouraging for balancing the selection of high germination rate and maintaining initial seed dormancy for PHS. If we assume that a malster, at the earliest, would start malting barley approximately 47 days after harvest from the field, we will want to select lines that maintain dormancy until 50-60 days post PM. Most non-dormant AlaAT haplotypes fit this profile for the 2020 and 2021 crop year. However, given the substantial dormancy we observed in 2021, we must be careful in considering how it relates to our PHS values observed for that same year. PHS will need to be tested in multiple years where conditions would develop less dormant barley. If we continue to have low PHS mean and variation across multiple years with potentially differing levels of dormancy per year, we can then focus the selection pressure to increase germination rate with less concern of reducing our PHS resistance for the given AlaAT haplotypes.

# Discussion

Important point- cooler temperatures during grainfill for winter barley could be a pereptual inducment of longer dormancy

# Conclusion

# 
